import type { Sprache } from '../lib/sprache'

// Vorbestell-Seite /anlagen (AnlagenPage.vue), Hypothese H3
const de = {
  // Das Produkt ist noch nicht gebaut: Hinweis über dem Titel, Texte im Futur, kein Gratis-Test
  inEntwicklung: 'In Entwicklung: noch nicht in der App, jetzt vorbestellen',
  titel: 'Wartungsplan für Liegenschaften und Anlagen',
  problem: 'Wer Gebäude oder Anlagen unterhält, verliert Fristen in Excel-Listen und Belege in Ordnern. Der Wartungsplan wird an jede Wartung und Prüfung erinnern, das Foto der Rechnung wird zum Eintrag, das Protokoll zum PDF.',
  // Grafiken (GrafikAblauf, GrafikVorherNachher): `bild` ist der <title> der SVG, Wörter höchstens 14 Zeichen
  ablauf: {
    titel: 'So wird es funktionieren',
    bild: 'Ablauf in vier Schritten: Anlage erfassen, Fristen und Intervalle hinterlegen, Erinnerung vor Ablauf, Nachweis bei der Kontrolle',
    schritte: [
      { ort: 'Erfassen', text: 'Anlage beim Objekt erfassen', eigen: false },
      { ort: 'Hinterlegen', text: 'Fristen und Intervalle eintragen', eigen: false },
      { ort: 'Erinnern', text: 'E-Mail rechtzeitig vor Ablauf', eigen: true },
      { ort: 'Nachweisen', text: 'Protokoll als PDF für die Kontrolle', eigen: false },
    ],
  },
  vorherNachher: {
    titel: 'Was sich ändert',
    bild: 'Bisher und mit Wartungsheft: aus Zetteln, Kalender und Excel wird eine Liste mit allen Fristen, aus der verpassten Frist eine rechtzeitige Erinnerung, aus der Suche nach dem Nachweis ein fertiges Protokoll',
    bisher: 'Bisher',
    neu: 'Mit Wartungsheft',
    zeilen: [
      { bisher: 'Fristen auf Zetteln, im Kalender und in Excel-Listen', neu: 'Eine Liste mit allen Fristen pro Objekt' },
      { bisher: 'Eine Prüffrist geht vergessen', neu: 'Eine E-Mail erinnert rechtzeitig' },
      { bisher: 'Belege im Ordner suchen, wenn die Kontrolle kommt', neu: 'Das Protokoll liegt als PDF bereit' },
    ],
  },
  benefits: [
    { icon: 'pi-calendar', title: 'Jede Frist im Blick', text: 'Heizung, Lift, Lüftung, Brandmelder, Maschinen: Wartungsintervalle und gesetzliche Prüffristen pro Objekt, eine E-Mail wird rechtzeitig erinnern.' },
    { icon: 'pi-camera', title: 'Rechnung oder Prüfbericht fotografieren', text: 'Firma, Datum und Betrag werden ausgelesen und dem Objekt zugeordnet. Die Historie wird sich von selbst füllen.' },
    { icon: 'pi-file-pdf', title: 'Protokoll auf Knopfdruck', text: 'Wartungshistorie und Prüfprotokoll werden als PDF für Eigentümer, Verwaltung und Versicherung bereitstehen.' },
  ],
  fuerWenTitel: 'Für wen',
  fuerWen: 'Hauswartungen und Facility-Betriebe, Liegenschaftsverwaltungen mit wenigen Mitarbeitenden, Werkstätten, Gärtnereien, Gemeinden, Vereine und Kirchgemeinden mit eigenen Gebäuden. Nicht für Industrieanlagen mit Ticketsystem, dafür gibt es andere.',
  preis: '36 CHF pro Objekt und Jahr',
  preisHinweis: 'Ab 20 Objekten günstiger, keine Benutzergebühren, Jahresrechnung mit QR-Zahlteil auf die Firma.',
  vorbestellung: 'Wir bauen ab der ersten Bestellung. Lieferung vier Wochen nach deiner Bestellung, du zahlst erst bei Lieferung. Schreib uns, wie viele Objekte du betreust und womit du heute arbeitest.',
  knopf: 'Vorbestellen per E-Mail',
  kontaktVor: 'Fragen vorab? Schreib an',
  kontaktNach: ', wir antworten am gleichen Tag.',
  mailBetreff: 'Vorbestellung Wartungsplan für Anlagen',
  mailText: 'Betrieb: \nAnzahl Objekte: \nHeutiges Werkzeug (Excel, Papier, Software): \n',
}

export default {
  de,
  fr: {
    inEntwicklung: 'En développement : pas encore dans l’app, précommandez maintenant',
    titel: 'Plan d’entretien pour immeubles et installations',
    problem: 'Qui entretient des bâtiments ou des installations perd des délais dans des listes Excel et des justificatifs dans des classeurs. Le plan d’entretien rappellera chaque entretien et chaque contrôle, la photo de la facture deviendra une entrée, le procès-verbal un PDF.',
    ablauf: {
      titel: 'Comment ça fonctionnera',
      bild: 'Déroulement en quatre étapes : saisir l’installation, enregistrer délais et intervalles, rappel avant l’échéance, preuve lors du contrôle',
      schritte: [
        { ort: 'Saisir', text: 'Saisir l’installation de l’objet', eigen: false },
        { ort: 'Enregistrer', text: 'Délais et intervalles d’entretien', eigen: false },
        { ort: 'Rappeler', text: 'E-mail à temps avant l’échéance', eigen: true },
        { ort: 'Prouver', text: 'Procès-verbal PDF pour le contrôle', eigen: false },
      ],
    },
    vorherNachher: {
      titel: 'Ce qui change',
      bild: 'Avant et avec Wartungsheft : les notes, l’agenda et Excel deviennent une liste avec tous les délais, le délai manqué un rappel à temps, la recherche du justificatif un procès-verbal prêt',
      bisher: 'Avant',
      neu: 'Avec Wartungsheft',
      zeilen: [
        { bisher: 'Délais sur des notes, dans l’agenda et des listes Excel', neu: 'Une liste avec tous les délais par objet' },
        { bisher: 'Un délai de contrôle est oublié', neu: 'Un e-mail rappelle à temps' },
        { bisher: 'Chercher les justificatifs dans les classeurs au moment du contrôle', neu: 'Le procès-verbal est prêt en PDF' },
      ],
    },
    benefits: [
      { icon: 'pi-calendar', title: 'Chaque délai sous contrôle', text: 'Chauffage, ascenseur, ventilation, détecteurs incendie, machines : intervalles d’entretien et délais de contrôle légaux par objet, un e-mail rappellera à temps.' },
      { icon: 'pi-camera', title: 'Photographier la facture ou le rapport de contrôle', text: 'Entreprise, date et montant seront lus et attribués à l’objet. L’historique se remplira tout seul.' },
      { icon: 'pi-file-pdf', title: 'Procès-verbal en un clic', text: 'Historique d’entretien et procès-verbal de contrôle seront prêts en PDF pour propriétaires, gérance et assurance.' },
    ],
    fuerWenTitel: 'Pour qui',
    fuerWen: 'Conciergeries et entreprises de facility management, gérances immobilières avec peu de collaborateurs, ateliers, entreprises horticoles, communes, associations et paroisses avec leurs propres bâtiments. Pas pour les installations industrielles avec système de tickets, d’autres outils existent pour cela.',
    preis: '36 CHF par objet et par an',
    preisHinweis: 'Moins cher dès 20 objets, sans frais par utilisateur, facture annuelle avec section de paiement QR au nom de l’entreprise.',
    vorbestellung: 'Nous développons dès la première commande. Livraison quatre semaines après votre commande, vous ne payez qu’à la livraison. Écrivez-nous combien d’objets vous gérez et avec quel outil vous travaillez aujourd’hui.',
    knopf: 'Précommander par e-mail',
    kontaktVor: 'Des questions ? Écrivez à',
    kontaktNach: ', nous répondons le jour même.',
    mailBetreff: 'Précommande plan d’entretien pour installations',
    mailText: 'Entreprise : \nNombre d’objets : \nOutil actuel (Excel, papier, logiciel) : \n',
  },
  it: {
    inEntwicklung: 'In sviluppo: non ancora nell\'app, preordina ora',
    titel: 'Piano di manutenzione per immobili e impianti',
    problem: 'Chi gestisce edifici o impianti perde scadenze nelle liste Excel e documenti nei classificatori. Il piano di manutenzione ricorderà ogni manutenzione e ogni controllo, la foto della fattura diventerà una registrazione, il verbale un PDF.',
    ablauf: {
      titel: 'Come funzionerà',
      bild: 'Procedura in quattro passi: registrare l\'impianto, inserire scadenze e intervalli, promemoria prima della scadenza, prova al controllo',
      schritte: [
        { ort: 'Registrare', text: 'Registra l\'impianto dell\'oggetto', eigen: false },
        { ort: 'Inserire', text: 'Scadenze e intervalli di manutenzione', eigen: false },
        { ort: 'Ricordare', text: 'E-mail in tempo prima della scadenza', eigen: true },
        { ort: 'Dimostrare', text: 'Verbale in PDF per il controllo', eigen: false },
      ],
    },
    vorherNachher: {
      titel: 'Cosa cambia',
      bild: 'Prima e con Wartungsheft: foglietti, calendario ed Excel diventano una lista con tutte le scadenze, la scadenza mancata un promemoria in tempo, la ricerca del documento un verbale pronto',
      bisher: 'Prima',
      neu: 'Con Wartungsheft',
      zeilen: [
        { bisher: 'Scadenze su foglietti, nel calendario e in liste Excel', neu: 'Una lista con tutte le scadenze per oggetto' },
        { bisher: 'Una scadenza di controllo viene dimenticata', neu: 'Un\'e-mail ricorda in tempo' },
        { bisher: 'Cercare i documenti nei classificatori quando arriva il controllo', neu: 'Il verbale è pronto in PDF' },
      ],
    },
    benefits: [
      { icon: 'pi-calendar', title: 'Ogni scadenza sotto controllo', text: 'Riscaldamento, ascensore, ventilazione, rilevatori d\'incendio, macchine: intervalli di manutenzione e scadenze di controllo legali per oggetto, un\'e-mail ricorderà in tempo.' },
      { icon: 'pi-camera', title: 'Fotografa la fattura o il rapporto di controllo', text: 'Ditta, data e importo verranno letti e assegnati all\'oggetto. Lo storico si riempirà da solo.' },
      { icon: 'pi-file-pdf', title: 'Verbale con un clic', text: 'Storico di manutenzione e verbale di controllo saranno pronti in PDF per proprietari, amministrazione e assicurazione.' },
    ],
    fuerWenTitel: 'Per chi',
    fuerWen: 'Custodi e aziende di facility management, amministrazioni immobiliari con pochi collaboratori, officine, aziende di giardinaggio, comuni, associazioni e parrocchie con edifici propri. Non per impianti industriali con sistema di ticket, per quelli esistono altri strumenti.',
    preis: '36 CHF per oggetto e anno',
    preisHinweis: 'Più conveniente da 20 oggetti, nessun costo per utente, fattura annuale con sezione di pagamento QR intestata alla ditta.',
    vorbestellung: 'Sviluppiamo dalla prima ordinazione. Consegna quattro settimane dopo la tua ordinazione, paghi solo alla consegna. Scrivici quanti oggetti gestisci e con cosa lavori oggi.',
    knopf: 'Preordina via e-mail',
    kontaktVor: 'Domande? Scrivi a',
    kontaktNach: ', rispondiamo il giorno stesso.',
    mailBetreff: 'Preordine piano di manutenzione per impianti',
    mailText: 'Azienda: \nNumero di oggetti: \nStrumento attuale (Excel, carta, software): \n',
  },
  en: {
    inEntwicklung: 'In development: not in the app yet, pre-order now',
    titel: 'Maintenance plan for buildings and equipment',
    problem: 'Anyone who looks after buildings or equipment loses deadlines in Excel lists and receipts in binders. The maintenance plan will remind you of every service and inspection, the photo of the invoice will become an entry, the report a PDF.',
    ablauf: {
      titel: 'How it will work',
      bild: 'Four steps: record the equipment, set deadlines and intervals, reminder before they expire, proof at the inspection',
      schritte: [
        { ort: 'Record', text: 'Add the equipment to the property', eigen: false },
        { ort: 'Set', text: 'Deadlines and service intervals', eigen: false },
        { ort: 'Remind', text: 'Email in good time before expiry', eigen: true },
        { ort: 'Prove', text: 'PDF report as proof at the inspection', eigen: false },
      ],
    },
    vorherNachher: {
      titel: 'What changes',
      bild: 'Before and with Wartungsheft: notes, calendar and Excel become one list with every deadline, the missed deadline a timely reminder, the search for proof a ready report',
      bisher: 'Before',
      neu: 'With Wartungsheft',
      zeilen: [
        { bisher: 'Deadlines on notes, in the calendar and in Excel lists', neu: 'One list with every deadline per property' },
        { bisher: 'An inspection deadline is missed', neu: 'An email reminds you in good time' },
        { bisher: 'Searching binders for receipts when the inspection comes', neu: 'The report is ready as a PDF' },
      ],
    },
    benefits: [
      { icon: 'pi-calendar', title: 'Every deadline in view', text: 'Heating, lift, ventilation, fire detectors, machines: maintenance intervals and statutory inspection deadlines per property, an email will remind you in good time.' },
      { icon: 'pi-camera', title: 'Photograph the invoice or inspection report', text: 'Company, date and amount will be read out and assigned to the property. The history will fill itself.' },
      { icon: 'pi-file-pdf', title: 'Report at the push of a button', text: 'Maintenance history and inspection report will be ready as PDF for owners, property management and insurance.' },
    ],
    fuerWenTitel: 'Who it is for',
    fuerWen: 'Caretaking and facility management firms, property managers with a small team, workshops, garden centres, municipalities, clubs and parishes with their own buildings. Not for industrial plants with a ticketing system, others cover that.',
    preis: 'CHF 36 per property and year',
    preisHinweis: 'Cheaper from 20 properties, no per-user fees, annual invoice with QR payment slip to the company.',
    vorbestellung: 'We build from the first order. Delivery four weeks after your order, you only pay on delivery. Tell us how many properties you look after and what you use today.',
    knopf: 'Pre-order by email',
    kontaktVor: 'Questions first? Write to',
    kontaktNach: ', we reply the same day.',
    mailBetreff: 'Pre-order maintenance plan for equipment',
    mailText: 'Company: \nNumber of properties: \nCurrent tool (Excel, paper, software): \n',
  },
} satisfies Record<Sprache, typeof de>
