import type { Sprache } from '../lib/sprache'

// Anmeldeseite (LoginPage.vue). Die Mail mit dem Code und die App danach sind deutsch.
const de = {
  willkommen: 'Willkommen zurück.',
  neu: 'Neu hier? 30 Tage alles gratis. Kein Passwort — wir schicken dir einen Code.',
  kunde: 'Schon Kunde? Gleiche E-Mail, gleiches Konto.',
  beschreibung: 'E-Mail-Adresse eingeben, der Anmelde-Code kommt per Mail. Wie wir mit deiner Adresse umgehen, steht in der',
  datenschutz: 'Datenschutzerklärung',
  email: 'E-Mail-Adresse',
  senden: 'Code senden',
  andere: 'Andere E-Mail',
  oder: 'oder',
  google: 'Mit Google anmelden',
  gesendet: 'Code wurde an',
  gesendetNach: ' gesendet.',
  code: '6-stelliger Code',
  anmelden: 'Anmelden',
  fehlerSenden: 'Code konnte nicht gesendet werden.',
  fehlerCode: 'Ungültiger Code.',
}

export default {
  de,
  fr: {
    willkommen: 'Bon retour.',
    neu: 'Nouveau ici ? 30 jours, tout gratuit. Pas de mot de passe : nous vous envoyons un code.',
    kunde: 'Déjà client ? Même e-mail, même compte.',
    beschreibung: 'Saisissez votre adresse e-mail, le code de connexion arrive par e-mail. La façon dont nous traitons votre adresse est décrite dans la',
    datenschutz: 'politique de confidentialité',
    email: 'Adresse e-mail',
    senden: 'Envoyer le code',
    andere: 'Autre e-mail',
    oder: 'ou',
    google: 'Se connecter avec Google',
    gesendet: 'Le code a été envoyé à',
    gesendetNach: '.',
    code: 'Code à 6 chiffres',
    anmelden: 'Se connecter',
    fehlerSenden: 'Le code n\'a pas pu être envoyé.',
    fehlerCode: 'Code non valable.',
  },
  it: {
    willkommen: 'Bentornato.',
    neu: 'Nuovo qui? 30 giorni tutto gratis. Nessuna password: ti inviamo un codice.',
    kunde: 'Già cliente? Stessa e-mail, stesso account.',
    beschreibung: 'Inserisci l\'indirizzo e-mail, il codice di accesso arriva via e-mail. Come trattiamo il tuo indirizzo è descritto nel documento',
    datenschutz: 'Informativa sulla privacy',
    email: 'Indirizzo e-mail',
    senden: 'Invia codice',
    andere: 'Altra e-mail',
    oder: 'oppure',
    google: 'Accedi con Google',
    gesendet: 'Il codice è stato inviato a',
    gesendetNach: '.',
    code: 'Codice a 6 cifre',
    anmelden: 'Accedi',
    fehlerSenden: 'Impossibile inviare il codice.',
    fehlerCode: 'Codice non valido.',
  },
  en: {
    willkommen: 'Welcome back.',
    neu: 'New here? Everything free for 30 days. No password: we send you a code.',
    kunde: 'Already a customer? Same email, same account.',
    beschreibung: 'Enter your email address and the sign-in code arrives by email. How we handle your address is explained in the',
    datenschutz: 'privacy policy',
    email: 'Email address',
    senden: 'Send code',
    andere: 'Different email',
    oder: 'or',
    google: 'Sign in with Google',
    gesendet: 'The code was sent to',
    gesendetNach: '.',
    code: '6-digit code',
    anmelden: 'Sign in',
    fehlerSenden: 'The code could not be sent.',
    fehlerCode: 'Invalid code.',
  },
} satisfies Record<Sprache, typeof de>
