import type { Sprache } from '../lib/sprache'

// Preistabelle (PriceTable.vue) und Beispiel-Fälligkeiten (DemoDueList.vue). Beträge rechnet die Komponente,
// die Texte nehmen sie als Parameter.
const de = {
  privat: 'Privat',
  betrieb: 'Betrieb',
  umschalter: 'Privat oder Betrieb',
  privatJahr: (preis: string) => `${preis} CHF im Jahr`,
  privatMonat: (monat: string, max: number) => `${monat} im Monat, bis ${max} Fahrzeuge`,
  privatIntro: (max: number) => `Ein Preis für dein Auto, das Motorrad und den Wohnwagen zusammen. 30 Tage gratis testen, mit allen Funktionen; danach brauchen nur KI-Scan und Chat das Abo. Mehr als ${max} Fahrzeuge? Dann gilt die Betriebsliste.`,
  betriebJahr: (preis: string) => `${preis} CHF pro Fahrzeug und Jahr`,
  betriebMonat: (monat: string) => `${monat} pro Fahrzeug und Monat, keine Grundgebühr, Jahresrechnung auf die Firma`,
  preisliste: 'Preisliste',
  fahrzeuge: 'Fahrzeuge',
  proJahr: 'pro Jahr',
  proMonat: 'pro Monat',
  anzahl: (n: number) => `${n} ${n === 1 ? 'Fahrzeug' : 'Fahrzeuge'}`,
  mehrAls: (max: number) => `mehr als ${max} Fahrzeuge`,
  aufAnfrage: 'auf Anfrage',
  testzeit: 'Die ersten 30 Tage sind gratis, mit allen Funktionen.',
  frage: 'Wie viele Fahrzeuge hat dein Betrieb?',
  regler: 'Fahrzeuge für die Preisrechnung',
  imJahr: (preis: string) => `${preis} im Jahr`,
  imMonat: (preis: string) => `${preis} im Monat`,
  inbegriffen: [
    'Scannen ohne Limit im Alltag, Chat-Assistent, E-Mail-Erinnerungen',
    'Kosten pro Fahrzeug und Jahr für Excel, PDF-Dossier, Serviceheft für den Verkauf',
    'Jahresrechnung, keine Grundgebühr, nichts verlängert sich von selbst, gleiche Funktionen für alle',
  ],
  demo: {
    beschreibung: 'Beispiel: Fälligkeiten eines Fahrzeugs',
    ueberfaellig: '1 überfällig',
    fuss: 'Beispiel-Ansicht aus der Übersicht',
    zeilen: [
      { label: 'Ölwechsel', caption: 'nächste am 14.03.2027 oder bei 92\'000 km', status: 'OK' },
      { label: 'Bremsen', caption: 'fällig am 05.10.2026', status: 'Bald fällig' },
      { label: 'MFK', caption: 'fällig seit 01.08.2026', status: 'Überfällig' },
    ],
  },
}

export default {
  de,
  fr: {
    privat: 'Particulier',
    betrieb: 'Entreprise',
    umschalter: 'Particulier ou entreprise',
    privatJahr: preis => `${preis} CHF par an`,
    privatMonat: (monat, max) => `${monat} par mois, jusqu’à ${max} véhicules`,
    privatIntro: max => `Un seul prix pour votre voiture, la moto et la caravane ensemble. 30 jours d’essai gratuit avec toutes les fonctions ; ensuite, seuls le scan IA et le chat nécessitent l’abonnement. Plus de ${max} véhicules ? C’est alors le tarif entreprise qui s’applique.`,
    betriebJahr: preis => `${preis} CHF par véhicule et par an`,
    betriebMonat: monat => `${monat} par véhicule et par mois, sans taxe de base, facture annuelle au nom de l’entreprise`,
    preisliste: 'Liste de prix',
    fahrzeuge: 'Véhicules',
    proJahr: 'par an',
    proMonat: 'par mois',
    anzahl: n => `${n} ${n === 1 ? 'véhicule' : 'véhicules'}`,
    mehrAls: max => `plus de ${max} véhicules`,
    aufAnfrage: 'sur demande',
    testzeit: 'Les 30 premiers jours sont gratuits, avec toutes les fonctions.',
    frage: 'Combien de véhicules compte votre entreprise ?',
    regler: 'Véhicules pour le calcul du prix',
    imJahr: preis => `${preis} par an`,
    imMonat: preis => `${preis} par mois`,
    inbegriffen: [
      'Scans illimités au quotidien, assistant de chat, rappels par e-mail',
      'Coûts par véhicule et par an pour Excel, dossier PDF, carnet d’entretien pour la vente',
      'Facture annuelle, sans taxe de base, rien ne se prolonge tout seul, mêmes fonctions pour tous',
    ],
    demo: {
      beschreibung: 'Exemple : échéances d’un véhicule',
      ueberfaellig: '1 en retard',
      fuss: 'Exemple de vue de l’aperçu',
      zeilen: [
        { label: 'Vidange', caption: 'prochaine le 14.03.2027 ou à 92 000 km', status: 'OK' },
        { label: 'Freins', caption: 'à faire le 05.10.2026', status: 'Bientôt' },
        { label: 'Expertise', caption: 'en retard depuis le 01.08.2026', status: 'En retard' },
      ],
    },
  },
  it: {
    privat: 'Privato',
    betrieb: 'Azienda',
    umschalter: 'Privato o azienda',
    privatJahr: preis => `${preis} CHF all'anno`,
    privatMonat: (monat, max) => `${monat} al mese, fino a ${max} veicoli`,
    privatIntro: max => `Un solo prezzo per la tua auto, la moto e la roulotte insieme. 30 giorni di prova gratuita con tutte le funzioni; dopo, solo la scansione IA e la chat richiedono l'abbonamento. Più di ${max} veicoli? Allora vale il listino aziende.`,
    betriebJahr: preis => `${preis} CHF per veicolo e anno`,
    betriebMonat: monat => `${monat} per veicolo al mese, senza tassa di base, fattura annuale intestata alla ditta`,
    preisliste: 'Listino prezzi',
    fahrzeuge: 'Veicoli',
    proJahr: 'all\'anno',
    proMonat: 'al mese',
    anzahl: n => `${n} ${n === 1 ? 'veicolo' : 'veicoli'}`,
    mehrAls: max => `più di ${max} veicoli`,
    aufAnfrage: 'su richiesta',
    testzeit: 'I primi 30 giorni sono gratis, con tutte le funzioni.',
    frage: 'Quanti veicoli ha la tua azienda?',
    regler: 'Veicoli per il calcolo del prezzo',
    imJahr: preis => `${preis} all'anno`,
    imMonat: preis => `${preis} al mese`,
    inbegriffen: [
      'Scansioni senza limiti nell\'uso quotidiano, assistente chat, promemoria via e-mail',
      'Costi per veicolo e anno per Excel, dossier PDF, libretto di manutenzione per la vendita',
      'Fattura annuale, senza tassa di base, niente si prolunga da solo, stesse funzioni per tutti',
    ],
    demo: {
      beschreibung: 'Esempio: scadenze di un veicolo',
      ueberfaellig: '1 scaduto',
      fuss: 'Vista di esempio dalla panoramica',
      zeilen: [
        { label: 'Cambio dell\'olio', caption: 'prossimo il 14.03.2027 o a 92\'000 km', status: 'OK' },
        { label: 'Freni', caption: 'scade il 05.10.2026', status: 'In scadenza' },
        { label: 'Collaudo', caption: 'scaduto dal 01.08.2026', status: 'Scaduto' },
      ],
    },
  },
  en: {
    privat: 'Private',
    betrieb: 'Business',
    umschalter: 'Private or business',
    privatJahr: preis => `CHF ${preis} a year`,
    privatMonat: (monat, max) => `${monat} a month, up to ${max} vehicles`,
    privatIntro: max => `One price for your car, motorbike and caravan together. Try free for 30 days with all features; after that only the AI scan and chat need the subscription. More than ${max} vehicles? Then the business price list applies.`,
    betriebJahr: preis => `CHF ${preis} per vehicle and year`,
    betriebMonat: monat => `${monat} per vehicle and month, no base fee, annual invoice to the company`,
    preisliste: 'Price list',
    fahrzeuge: 'Vehicles',
    proJahr: 'per year',
    proMonat: 'per month',
    anzahl: n => `${n} ${n === 1 ? 'vehicle' : 'vehicles'}`,
    mehrAls: max => `more than ${max} vehicles`,
    aufAnfrage: 'on request',
    testzeit: 'The first 30 days are free, with all features.',
    frage: 'How many vehicles does your business have?',
    regler: 'Vehicles for the price calculation',
    imJahr: preis => `${preis} a year`,
    imMonat: preis => `${preis} a month`,
    inbegriffen: [
      'Unlimited scanning in everyday use, chat assistant, email reminders',
      'Costs per vehicle and year for Excel, PDF dossier, service book for selling',
      'Annual invoice, no base fee, nothing extends by itself, the same features for everyone',
    ],
    demo: {
      beschreibung: 'Example: due dates of a vehicle',
      ueberfaellig: '1 overdue',
      fuss: 'Example view from the overview',
      zeilen: [
        { label: 'Oil change', caption: 'next on 14.03.2027 or at 92\'000 km', status: 'OK' },
        { label: 'Brakes', caption: 'due on 05.10.2026', status: 'Due soon' },
        { label: 'MFK', caption: 'overdue since 01.08.2026', status: 'Overdue' },
      ],
    },
  },
} satisfies Record<Sprache, typeof de>
