import type { Sprache } from '../../lib/sprache'

// Wiederkehrende Wörter der App (Knöpfe, Navigation, Einheiten). Seitenspezifisches steht in der eigenen Datei.
const de = {
  speichern: 'Speichern',
  abbrechen: 'Abbrechen',
  loeschen: 'Löschen',
  bearbeiten: 'Bearbeiten',
  schliessen: 'Schliessen',
  zurueck: 'Zurück',
  ja: 'Ja',
  nein: 'Nein',
  ok: 'OK',
  weiter: 'Weiter',
  fertig: 'Fertig',
  laden: 'Wird geladen …',
  fehler: 'Fehler',
  gespeichert: 'Gespeichert',
  geloescht: 'Gelöscht',
  unbekannt: 'unbekannt',
  heute: 'Heute',
  navigation: {
    menu: 'Menu',
    titel: 'Navigation',
    uebersicht: 'Übersicht',
    fahrzeuge: 'Fahrzeuge',
    assistent: 'KI-Assistent',
    einstellungen: 'Einstellungen',
    feedback: 'Fehler melden oder Wunsch',
    hilfe: 'Hilfe',
    abmelden: 'Abmelden',
  },
}

export default {
  de,
  fr: {
    speichern: 'Enregistrer',
    abbrechen: 'Annuler',
    loeschen: 'Supprimer',
    bearbeiten: 'Modifier',
    schliessen: 'Fermer',
    zurueck: 'Retour',
    ja: 'Oui',
    nein: 'Non',
    ok: 'OK',
    weiter: 'Continuer',
    fertig: 'Terminé',
    laden: 'Chargement …',
    fehler: 'Erreur',
    gespeichert: 'Enregistré',
    geloescht: 'Supprimé',
    unbekannt: 'inconnu',
    heute: 'Aujourd\'hui',
    navigation: {
      menu: 'Menu',
      titel: 'Navigation',
      uebersicht: 'Aperçu',
      fahrzeuge: 'Véhicules',
      assistent: 'Assistant IA',
      einstellungen: 'Réglages',
      feedback: 'Signaler un problème ou un souhait',
      hilfe: 'Aide',
      abmelden: 'Se déconnecter',
    },
  },
  it: {
    speichern: 'Salva',
    abbrechen: 'Annulla',
    loeschen: 'Elimina',
    bearbeiten: 'Modifica',
    schliessen: 'Chiudi',
    zurueck: 'Indietro',
    ja: 'Sì',
    nein: 'No',
    ok: 'OK',
    weiter: 'Avanti',
    fertig: 'Fatto',
    laden: 'Caricamento …',
    fehler: 'Errore',
    gespeichert: 'Salvato',
    geloescht: 'Eliminato',
    unbekannt: 'sconosciuto',
    heute: 'Oggi',
    navigation: {
      menu: 'Menu',
      titel: 'Navigazione',
      uebersicht: 'Panoramica',
      fahrzeuge: 'Veicoli',
      assistent: 'Assistente IA',
      einstellungen: 'Impostazioni',
      feedback: 'Segnala un errore o un desiderio',
      hilfe: 'Aiuto',
      abmelden: 'Esci',
    },
  },
  en: {
    speichern: 'Save',
    abbrechen: 'Cancel',
    loeschen: 'Delete',
    bearbeiten: 'Edit',
    schliessen: 'Close',
    zurueck: 'Back',
    ja: 'Yes',
    nein: 'No',
    ok: 'OK',
    weiter: 'Next',
    fertig: 'Done',
    laden: 'Loading …',
    fehler: 'Error',
    gespeichert: 'Saved',
    geloescht: 'Deleted',
    unbekannt: 'unknown',
    heute: 'Today',
    navigation: {
      menu: 'Menu',
      titel: 'Navigation',
      uebersicht: 'Overview',
      fahrzeuge: 'Vehicles',
      assistent: 'AI assistant',
      einstellungen: 'Settings',
      feedback: 'Report a problem or a wish',
      hilfe: 'Help',
      abmelden: 'Sign out',
    },
  },
} satisfies Record<Sprache, typeof de>
