import type { Sprache } from '../../lib/sprache'

// Jahresabo bestellen (components/OrderDialog.vue) und Fehler der Abo-Aktionen (services/ai-access.ts).
// Die Feldfehler kommen deutsch aus parseOrder bzw. dem AI-Proxy; in anderen Sprachen gelten diese hier pro Feld.
const de = {
  titel: 'Jahresabo bestellen',
  privat: 'Privat',
  betrieb: 'Betrieb',
  umschalter: 'Privat oder Betrieb',
  introBetrieb: (preis: string) => `${preis} pro Fahrzeug und Jahr, Rechnung auf die Firma.`,
  introPrivat: (preis: string, max: number) => `${preis} im Jahr für bis zu ${max} Fahrzeuge.`,
  introZahlbar: 'Du kannst sofort weiterarbeiten, die Rechnung kommt per Mail und ist in 30 Tagen zahlbar.',
  introTestzeit: (datum: string) => `Das bezahlte Jahr beginnt nach deiner Testzeit am ${datum}.`,
  firma: 'Firma',
  kontaktperson: 'Kontaktperson',
  name: 'Name',
  strasse: 'Strasse und Nummer',
  plz: 'PLZ',
  ort: 'Ort',
  email: 'E-Mail für die Rechnung',
  referenz: 'Deine Referenz (optional)',
  referenzBeispiel: 'z. B. Kostenstelle',
  fahrzeuge: 'Anzahl Fahrzeuge',
  proJahr: (preis: string) => `${preis} im Jahr`,
  ueberGrenze: (max: number, preis: string) => `Über ${max} Fahrzeuge gilt der Preis pro Fahrzeug, ${preis} im Jahr.`,
  bedingungen: 'Du bekommst eine Rechnung, zahlbar in 30 Tagen. Verbindlich wird das Abo erst mit deiner Zahlung, für ein Jahr; zahlst du nicht, musst du nichts tun. Nichts verlängert sich von selbst: Die Rechnung fürs nächste Jahr kommt 30 Tage vor Ablauf als Angebot, nach dem dann aktuellen Fahrzeugstand. Es gelten die',
  agb: 'AGB',
  agbNach: '.',
  bestellen: 'Rechnung anfordern',
  feldfehler: {
    audience: 'Privat oder Betrieb wählen.',
    company: 'Firma angeben.',
    contact: 'Name angeben.',
    street: 'Strasse und Nummer angeben.',
    zip: 'PLZ mit vier Ziffern angeben.',
    city: 'Ort angeben.',
    email: 'Gültige E-Mail-Adresse für die Rechnung angeben.',
    reference: 'Referenz prüfen.',
    vehicles: 'Mindestens ein Fahrzeug.',
    acceptTerms: 'Bitte den Bedingungen zustimmen.',
  },
  aboAktion: (status: number) => `Abo-Aktion nicht möglich (${status})`,
  checkout: (status: number) => `Checkout nicht möglich (${status})`,
  nutzung: (status: number) => `Nutzung konnte nicht geladen werden (${status})`,
  rueckmeldung: (status: number) => `Rückmeldung nicht gesendet (${status})`,
  diktat: (status: number) => `Diktat nicht erkannt (${status})`,
}

export default {
  de,
  fr: {
    titel: 'Commander l’abonnement annuel',
    privat: 'Particulier',
    betrieb: 'Entreprise',
    umschalter: 'Particulier ou entreprise',
    introBetrieb: (preis: string) => `${preis} par véhicule et par an, facture au nom de l’entreprise.`,
    introPrivat: (preis: string, max: number) => `${preis} par an pour jusqu’à ${max} véhicules.`,
    introZahlbar: 'Tu peux continuer à travailler tout de suite ; la facture arrive par e-mail, payable à 30 jours.',
    introTestzeit: (datum: string) => `L’année payante commence après ta période d’essai, le ${datum}.`,
    firma: 'Entreprise',
    kontaktperson: 'Personne de contact',
    name: 'Nom',
    strasse: 'Rue et numéro',
    plz: 'NPA',
    ort: 'Localité',
    email: 'E-mail pour la facture',
    referenz: 'Ta référence (facultatif)',
    referenzBeispiel: 'p. ex. centre de coûts',
    fahrzeuge: 'Nombre de véhicules',
    proJahr: (preis: string) => `${preis} par an`,
    ueberGrenze: (max: number, preis: string) => `Au-delà de ${max} véhicules, le prix par véhicule s’applique : ${preis} par an.`,
    bedingungen: 'Tu reçois une facture, payable à 30 jours. L’abonnement ne devient ferme qu’avec ton paiement, pour un an ; si tu ne paies pas, tu n’as rien à faire. Rien ne se prolonge tout seul : la facture pour l’année suivante arrive 30 jours avant l’échéance, comme une offre, selon le nombre de véhicules à ce moment-là. Les',
    agb: 'CG',
    agbNach: ' s’appliquent.',
    bestellen: 'Demander la facture',
    feldfehler: {
      audience: 'Choisis particulier ou entreprise.',
      company: 'Indique l’entreprise.',
      contact: 'Indique le nom.',
      street: 'Indique la rue et le numéro.',
      zip: 'Indique un NPA à quatre chiffres.',
      city: 'Indique la localité.',
      email: 'Indique une adresse e-mail valable pour la facture.',
      reference: 'Vérifie la référence.',
      vehicles: 'Au moins un véhicule.',
      acceptTerms: 'Accepte les conditions.',
    },
    aboAktion: (status: number) => `Action sur l’abonnement impossible (${status})`,
    checkout: (status: number) => `Paiement impossible (${status})`,
    nutzung: (status: number) => `Impossible de charger l’utilisation (${status})`,
    rueckmeldung: (status: number) => `Message non envoyé (${status})`,
    diktat: (status: number) => `Dictée non reconnue (${status})`,
  },
  it: {
    titel: 'Ordina l\'abbonamento annuale',
    privat: 'Privato',
    betrieb: 'Azienda',
    umschalter: 'Privato o azienda',
    introBetrieb: (preis: string) => `${preis} per veicolo e anno, fattura intestata alla ditta.`,
    introPrivat: (preis: string, max: number) => `${preis} all'anno per un massimo di ${max} veicoli.`,
    introZahlbar: 'Puoi continuare a lavorare subito; la fattura arriva per e-mail ed è pagabile entro 30 giorni.',
    introTestzeit: (datum: string) => `L'anno a pagamento inizia dopo il tuo periodo di prova, il ${datum}.`,
    firma: 'Ditta',
    kontaktperson: 'Persona di contatto',
    name: 'Nome',
    strasse: 'Via e numero',
    plz: 'NPA',
    ort: 'Località',
    email: 'E-mail per la fattura',
    referenz: 'Il tuo riferimento (facoltativo)',
    referenzBeispiel: 'p. es. centro di costo',
    fahrzeuge: 'Numero di veicoli',
    proJahr: (preis: string) => `${preis} all'anno`,
    ueberGrenze: (max: number, preis: string) => `Oltre ${max} veicoli vale il prezzo per veicolo: ${preis} all'anno.`,
    bedingungen: 'Ricevi una fattura, pagabile entro 30 giorni. L\'abbonamento diventa vincolante solo con il tuo pagamento, per un anno; se non paghi, non devi fare nulla. Nulla si prolunga da sé: la fattura per l\'anno successivo arriva 30 giorni prima della scadenza, come offerta, in base al numero di veicoli di quel momento. Valgono le',
    agb: 'CG',
    agbNach: '.',
    bestellen: 'Richiedi la fattura',
    feldfehler: {
      audience: 'Scegli privato o azienda.',
      company: 'Indica la ditta.',
      contact: 'Indica il nome.',
      street: 'Indica via e numero.',
      zip: 'Indica un NPA di quattro cifre.',
      city: 'Indica la località.',
      email: 'Indica un indirizzo e-mail valido per la fattura.',
      reference: 'Controlla il riferimento.',
      vehicles: 'Almeno un veicolo.',
      acceptTerms: 'Accetta le condizioni.',
    },
    aboAktion: (status: number) => `Operazione sull'abbonamento non possibile (${status})`,
    checkout: (status: number) => `Pagamento non possibile (${status})`,
    nutzung: (status: number) => `Impossibile caricare l'utilizzo (${status})`,
    rueckmeldung: (status: number) => `Messaggio non inviato (${status})`,
    diktat: (status: number) => `Dettatura non riconosciuta (${status})`,
  },
  en: {
    titel: 'Order annual subscription',
    privat: 'Private',
    betrieb: 'Business',
    umschalter: 'Private or business',
    introBetrieb: (preis: string) => `${preis} per vehicle and year, invoiced to the company.`,
    introPrivat: (preis: string, max: number) => `${preis} a year for up to ${max} vehicles.`,
    introZahlbar: 'You can keep working straight away; the invoice comes by email and is payable within 30 days.',
    introTestzeit: (datum: string) => `The paid year starts after your trial, on ${datum}.`,
    firma: 'Company',
    kontaktperson: 'Contact person',
    name: 'Name',
    strasse: 'Street and number',
    plz: 'Postcode',
    ort: 'Town',
    email: 'Email for the invoice',
    referenz: 'Your reference (optional)',
    referenzBeispiel: 'e.g. cost centre',
    fahrzeuge: 'Number of vehicles',
    proJahr: (preis: string) => `${preis} a year`,
    ueberGrenze: (max: number, preis: string) => `Above ${max} vehicles the per-vehicle price applies: ${preis} a year.`,
    bedingungen: 'You receive an invoice, payable within 30 days. The subscription only becomes binding with your payment, for one year; if you don\'t pay, you don\'t need to do anything. Nothing extends by itself: the invoice for the next year comes 30 days before expiry, as an offer, based on the number of vehicles at that time. The',
    agb: 'terms and conditions',
    agbNach: ' apply.',
    bestellen: 'Request invoice',
    feldfehler: {
      audience: 'Choose private or business.',
      company: 'Enter the company.',
      contact: 'Enter the name.',
      street: 'Enter street and number.',
      zip: 'Enter a four-digit postcode.',
      city: 'Enter the town.',
      email: 'Enter a valid email address for the invoice.',
      reference: 'Check the reference.',
      vehicles: 'At least one vehicle.',
      acceptTerms: 'Please accept the conditions.',
    },
    aboAktion: (status: number) => `Subscription action not possible (${status})`,
    checkout: (status: number) => `Checkout not possible (${status})`,
    nutzung: (status: number) => `Usage could not be loaded (${status})`,
    rueckmeldung: (status: number) => `Message not sent (${status})`,
    diktat: (status: number) => `Dictation not recognised (${status})`,
  },
} satisfies Record<Sprache, typeof de>
