import type { Sprache } from '../../lib/sprache'

// KI-Assistent: ChatDrawer.vue, ToolResultCard.vue und die Texte, die chat.ts dem Nutzer zeigt (Begrüssung,
// Ergebnisse der Werkzeuge, Ersatztext ohne Modellantwort). Prompts an das Modell stehen in services/prompts.ts.
const de = {
  titel: 'KI-Assistent',
  chatLoeschen: 'Chat löschen',
  dateienAblegen: 'Dateien hier ablegen',
  du: 'Du',
  assistent: 'Assistent',
  ja: 'Ja',
  jaPasst: 'Ja, passt',
  dropHinweis: 'Dateien hierher ziehen oder klicken',
  dateiAnhaengen: 'Datei anhängen',
  fotoAufnehmen: 'Foto aufnehmen',
  maximieren: 'Chat maximieren',
  diktieren: 'Nachricht diktieren',
  platzhalter: 'Nachricht...',
  bitteErfassen: 'Bitte erfassen',
  diktat: 'Diktat',
  fehler: 'Fehler',
  pdfZuGross: (mb: string) => `PDF zu gross (${mb} MB). Maximum: 50 MB.`,
  erledigt: 'Erledigt.',
  keineErgebnisse: 'Keine Ergebnisse.',
  vorschlaege: [
    { label: 'Rechnung scannen', prompt: 'Ich möchte eine Rechnung scannen' },
    { label: 'Fahrzeug anlegen', prompt: 'Neues Fahrzeug anlegen' },
    { label: 'Wartungsstatus', prompt: 'Zeige den Wartungsstatus meiner Fahrzeuge' },
  ],
  begruessung: (erstes: string, zweites: string) => `Hallo! Schick mir ein Foto der Werkstattrechnung, ich trage sie ein. Oder frag mich, zum Beispiel:

- «Wann muss der ${erstes} zum Service?»
- «Was hat der ${zweites} dieses Jahr gekostet?»
- «Trag ein: Ölwechsel gestern bei 68'500 km»

Fahrzeugausweis, Kaufvertrag und Serviceheft kann ich ebenfalls lesen.`,
  /** Ergebnisse der Werkzeuge (Karte und Ersatztext, wenn das Modell nichts schreibt) */
  werkzeug: {
    fahrzeugAngelegt: 'Fahrzeug angelegt',
    aktualisiert: (name: string) => `${name} aktualisiert`,
    fahrzeugGeloescht: 'Fahrzeug gelöscht',
    fahrzeugNichtGefunden: 'Fahrzeug nicht gefunden',
    planGespeichert: (name: string, anzahl: number) => `Wartungsplan für ${name} gespeichert (${anzahl} Positionen)`,
    monate: (anzahl: number) => `${anzahl} Monate`,
    rechnungExistiert: (werkstatt: string, datum: string, betrag: string) => `Diese Rechnung existiert bereits: ${werkstatt}, ${datum}, ${betrag}. Keine doppelte Erfassung.`,
    rechnungErfasst: 'Rechnung erfasst',
    rechnungNichtGefunden: 'Rechnung nicht gefunden',
    rechnungGeloescht: 'Rechnung gelöscht',
    keinOcr: 'Kein OCR-Text für diese Rechnung vorhanden',
    ocrFehlt: 'OCR-Cache-Eintrag nicht gefunden',
    wartungEingetragen: 'Wartung eingetragen',
    // Ersatztext aus den Ergebnissen
    marke: 'Marke',
    modell: 'Modell',
    baujahr: 'Baujahr',
    kilometerstand: 'Kilometerstand',
    kontrollschild: 'Kontrollschild',
    werkstatt: 'Werkstatt',
    datum: 'Datum',
    betrag: 'Betrag',
    positionen: 'Positionen',
    typ: 'Typ',
    beschreibung: 'Beschreibung',
    geloescht: 'Gelöscht',
    rechnungenUndWartungen: (rechnungen: number, wartungen: number) => `${rechnungen} Rechnungen, ${wartungen} Wartungen`,
    rechnungVon: (werkstatt: string) => `Rechnung von ${werkstatt}`,
  },
  /** ToolResultCard */
  karte: {
    fahrzeug: 'Fahrzeug',
    rechnung: 'Rechnung',
    wartung: 'Wartung',
    wartungsplan: 'Wartungsplan',
    geloescht: 'Gelöscht',
    ergebnis: 'Ergebnis',
    intervalle: (anzahl: number) => `${anzahl} Wartungsintervalle`,
    position: 'Position',
    betrag: 'Betrag',
    intervall: 'Intervall',
    felder: {
      make: 'Marke',
      model: 'Modell',
      year: 'Baujahr',
      mileage: 'Kilometerstand',
      licensePlate: 'Kennzeichen',
      vin: 'VIN',
      workshopName: 'Werkstatt',
      date: 'Datum',
      totalAmount: 'Betrag',
      currency: 'Währung',
      mileageAtService: 'Kilometerstand',
      type: 'Typ',
      description: 'Beschreibung',
      doneAt: 'Datum',
      message: 'Info',
      label: 'Bezeichnung',
      interval: 'Intervall',
      category: 'Kategorie',
      amount: 'Betrag',
    },
  },
}

export default {
  de,
  fr: {
    titel: 'Assistant IA',
    chatLoeschen: 'Effacer le chat',
    dateienAblegen: 'Dépose les fichiers ici',
    du: 'Toi',
    assistent: 'Assistant',
    ja: 'Oui',
    jaPasst: 'Oui, c\'est juste',
    dropHinweis: 'Glisse des fichiers ici ou clique',
    dateiAnhaengen: 'Joindre un fichier',
    fotoAufnehmen: 'Prendre une photo',
    maximieren: 'Agrandir le chat',
    diktieren: 'Dicter un message',
    platzhalter: 'Message...',
    bitteErfassen: 'Merci de saisir',
    diktat: 'Dictée',
    fehler: 'Erreur',
    pdfZuGross: (mb: string) => `PDF trop volumineux (${mb} Mo). Maximum : 50 Mo.`,
    erledigt: 'C\'est fait.',
    keineErgebnisse: 'Aucun résultat.',
    vorschlaege: [
      { label: 'Scanner une facture', prompt: 'Je veux scanner une facture' },
      { label: 'Ajouter un véhicule', prompt: 'Ajouter un nouveau véhicule' },
      { label: 'État de l\'entretien', prompt: 'Montre l\'état de l\'entretien de mes véhicules' },
    ],
    begruessung: (erstes: string, zweites: string) => `Salut ! Envoie-moi une photo de la facture du garage, je la saisis pour toi. Ou pose-moi une question, par exemple :

- « Quand la ${erstes} doit-elle aller au service ? »
- « Combien la ${zweites} a-t-elle coûté cette année ? »
- « Saisis : vidange hier à 68'500 km »

Je sais aussi lire le permis de circulation, le contrat de vente et le carnet d'entretien.`,
    werkzeug: {
      fahrzeugAngelegt: 'Véhicule ajouté',
      aktualisiert: (name: string) => `${name} mis à jour`,
      fahrzeugGeloescht: 'Véhicule supprimé',
      fahrzeugNichtGefunden: 'Véhicule introuvable',
      planGespeichert: (name: string, anzahl: number) => `Plan d'entretien enregistré pour ${name} (${anzahl} positions)`,
      monate: (anzahl: number) => `${anzahl} mois`,
      rechnungExistiert: (werkstatt: string, datum: string, betrag: string) => `Cette facture existe déjà : ${werkstatt}, ${datum}, ${betrag}. Pas de doublon.`,
      rechnungErfasst: 'Facture saisie',
      rechnungNichtGefunden: 'Facture introuvable',
      rechnungGeloescht: 'Facture supprimée',
      keinOcr: 'Aucun texte OCR pour cette facture',
      ocrFehlt: 'Entrée OCR introuvable',
      wartungEingetragen: 'Entretien enregistré',
      marke: 'Marque',
      modell: 'Modèle',
      baujahr: 'Année',
      kilometerstand: 'Kilométrage',
      kontrollschild: 'Plaque',
      werkstatt: 'Garage',
      datum: 'Date',
      betrag: 'Montant',
      positionen: 'Positions',
      typ: 'Type',
      beschreibung: 'Description',
      geloescht: 'Supprimé',
      rechnungenUndWartungen: (rechnungen: number, wartungen: number) => `${rechnungen} factures, ${wartungen} entretiens`,
      rechnungVon: (werkstatt: string) => `Facture de ${werkstatt}`,
    },
    karte: {
      fahrzeug: 'Véhicule',
      rechnung: 'Facture',
      wartung: 'Entretien',
      wartungsplan: 'Plan d\'entretien',
      geloescht: 'Supprimé',
      ergebnis: 'Résultat',
      intervalle: (anzahl: number) => `${anzahl} intervalles d'entretien`,
      position: 'Position',
      betrag: 'Montant',
      intervall: 'Intervalle',
      felder: {
        make: 'Marque',
        model: 'Modèle',
        year: 'Année',
        mileage: 'Kilométrage',
        licensePlate: 'Plaque',
        vin: 'N° de châssis',
        workshopName: 'Garage',
        date: 'Date',
        totalAmount: 'Montant',
        currency: 'Monnaie',
        mileageAtService: 'Kilométrage',
        type: 'Type',
        description: 'Description',
        doneAt: 'Date',
        message: 'Info',
        label: 'Désignation',
        interval: 'Intervalle',
        category: 'Catégorie',
        amount: 'Montant',
      },
    },
  },
  it: {
    titel: 'Assistente IA',
    chatLoeschen: 'Cancella chat',
    dateienAblegen: 'Rilascia i file qui',
    du: 'Tu',
    assistent: 'Assistente',
    ja: 'Sì',
    jaPasst: 'Sì, va bene',
    dropHinweis: 'Trascina qui i file o fai clic',
    dateiAnhaengen: 'Allega file',
    fotoAufnehmen: 'Scatta una foto',
    maximieren: 'Ingrandisci chat',
    diktieren: 'Detta un messaggio',
    platzhalter: 'Messaggio...',
    bitteErfassen: 'Per favore registra',
    diktat: 'Dettatura',
    fehler: 'Errore',
    pdfZuGross: (mb: string) => `PDF troppo grande (${mb} MB). Massimo: 50 MB.`,
    erledigt: 'Fatto.',
    keineErgebnisse: 'Nessun risultato.',
    vorschlaege: [
      { label: 'Scansiona fattura', prompt: 'Voglio scansionare una fattura' },
      { label: 'Aggiungi veicolo', prompt: 'Aggiungi un nuovo veicolo' },
      { label: 'Stato manutenzione', prompt: 'Mostra lo stato di manutenzione dei miei veicoli' },
    ],
    begruessung: (erstes: string, zweites: string) => `Ciao! Mandami una foto della fattura dell'officina e la registro io. Oppure chiedimi, per esempio:

- «Quando deve andare in servizio la ${erstes}?»
- «Quanto è costata quest'anno la ${zweites}?»
- «Registra: cambio dell'olio ieri a 68'500 km»

So leggere anche la licenza di circolazione, il contratto di vendita e il libretto di manutenzione.`,
    werkzeug: {
      fahrzeugAngelegt: 'Veicolo aggiunto',
      aktualisiert: (name: string) => `${name} aggiornato`,
      fahrzeugGeloescht: 'Veicolo eliminato',
      fahrzeugNichtGefunden: 'Veicolo non trovato',
      planGespeichert: (name: string, anzahl: number) => `Piano di manutenzione salvato per ${name} (${anzahl} voci)`,
      monate: (anzahl: number) => `${anzahl} mesi`,
      rechnungExistiert: (werkstatt: string, datum: string, betrag: string) => `Questa fattura esiste già: ${werkstatt}, ${datum}, ${betrag}. Nessuna registrazione doppia.`,
      rechnungErfasst: 'Fattura registrata',
      rechnungNichtGefunden: 'Fattura non trovata',
      rechnungGeloescht: 'Fattura eliminata',
      keinOcr: 'Nessun testo OCR per questa fattura',
      ocrFehlt: 'Voce OCR non trovata',
      wartungEingetragen: 'Manutenzione registrata',
      marke: 'Marca',
      modell: 'Modello',
      baujahr: 'Anno',
      kilometerstand: 'Chilometraggio',
      kontrollschild: 'Targa',
      werkstatt: 'Officina',
      datum: 'Data',
      betrag: 'Importo',
      positionen: 'Voci',
      typ: 'Tipo',
      beschreibung: 'Descrizione',
      geloescht: 'Eliminato',
      rechnungenUndWartungen: (rechnungen: number, wartungen: number) => `${rechnungen} fatture, ${wartungen} manutenzioni`,
      rechnungVon: (werkstatt: string) => `Fattura di ${werkstatt}`,
    },
    karte: {
      fahrzeug: 'Veicolo',
      rechnung: 'Fattura',
      wartung: 'Manutenzione',
      wartungsplan: 'Piano di manutenzione',
      geloescht: 'Eliminato',
      ergebnis: 'Risultato',
      intervalle: (anzahl: number) => `${anzahl} intervalli di manutenzione`,
      position: 'Voce',
      betrag: 'Importo',
      intervall: 'Intervallo',
      felder: {
        make: 'Marca',
        model: 'Modello',
        year: 'Anno',
        mileage: 'Chilometraggio',
        licensePlate: 'Targa',
        vin: 'N. di telaio',
        workshopName: 'Officina',
        date: 'Data',
        totalAmount: 'Importo',
        currency: 'Valuta',
        mileageAtService: 'Chilometraggio',
        type: 'Tipo',
        description: 'Descrizione',
        doneAt: 'Data',
        message: 'Info',
        label: 'Denominazione',
        interval: 'Intervallo',
        category: 'Categoria',
        amount: 'Importo',
      },
    },
  },
  en: {
    titel: 'AI assistant',
    chatLoeschen: 'Clear chat',
    dateienAblegen: 'Drop files here',
    du: 'You',
    assistent: 'Assistant',
    ja: 'Yes',
    jaPasst: 'Yes, that\'s right',
    dropHinweis: 'Drag files here or click',
    dateiAnhaengen: 'Attach file',
    fotoAufnehmen: 'Take a photo',
    maximieren: 'Maximise chat',
    diktieren: 'Dictate a message',
    platzhalter: 'Message...',
    bitteErfassen: 'Please record this',
    diktat: 'Dictation',
    fehler: 'Error',
    pdfZuGross: (mb: string) => `PDF too large (${mb} MB). Maximum: 50 MB.`,
    erledigt: 'Done.',
    keineErgebnisse: 'No results.',
    vorschlaege: [
      { label: 'Scan invoice', prompt: 'I want to scan an invoice' },
      { label: 'Add vehicle', prompt: 'Add a new vehicle' },
      { label: 'Maintenance status', prompt: 'Show the maintenance status of my vehicles' },
    ],
    begruessung: (erstes: string, zweites: string) => `Hello! Send me a photo of the garage invoice and I'll record it. Or ask me, for example:

- "When is the ${erstes} due for a service?"
- "How much did the ${zweites} cost this year?"
- "Record: oil change yesterday at 68,500 km"

I can also read the vehicle registration document, purchase contract and service book.`,
    werkzeug: {
      fahrzeugAngelegt: 'Vehicle added',
      aktualisiert: (name: string) => `${name} updated`,
      fahrzeugGeloescht: 'Vehicle deleted',
      fahrzeugNichtGefunden: 'Vehicle not found',
      planGespeichert: (name: string, anzahl: number) => `Maintenance schedule saved for ${name} (${anzahl} items)`,
      monate: (anzahl: number) => `${anzahl} months`,
      rechnungExistiert: (werkstatt: string, datum: string, betrag: string) => `This invoice already exists: ${werkstatt}, ${datum}, ${betrag}. Not recorded twice.`,
      rechnungErfasst: 'Invoice recorded',
      rechnungNichtGefunden: 'Invoice not found',
      rechnungGeloescht: 'Invoice deleted',
      keinOcr: 'No OCR text available for this invoice',
      ocrFehlt: 'OCR entry not found',
      wartungEingetragen: 'Maintenance recorded',
      marke: 'Make',
      modell: 'Model',
      baujahr: 'Year',
      kilometerstand: 'Mileage',
      kontrollschild: 'Number plate',
      werkstatt: 'Garage',
      datum: 'Date',
      betrag: 'Amount',
      positionen: 'Items',
      typ: 'Type',
      beschreibung: 'Description',
      geloescht: 'Deleted',
      rechnungenUndWartungen: (rechnungen: number, wartungen: number) => `${rechnungen} invoices, ${wartungen} maintenance entries`,
      rechnungVon: (werkstatt: string) => `Invoice from ${werkstatt}`,
    },
    karte: {
      fahrzeug: 'Vehicle',
      rechnung: 'Invoice',
      wartung: 'Maintenance',
      wartungsplan: 'Maintenance schedule',
      geloescht: 'Deleted',
      ergebnis: 'Result',
      intervalle: (anzahl: number) => `${anzahl} maintenance intervals`,
      position: 'Item',
      betrag: 'Amount',
      intervall: 'Interval',
      felder: {
        make: 'Make',
        model: 'Model',
        year: 'Year',
        mileage: 'Mileage',
        licensePlate: 'Number plate',
        vin: 'VIN',
        workshopName: 'Garage',
        date: 'Date',
        totalAmount: 'Amount',
        currency: 'Currency',
        mileageAtService: 'Mileage',
        type: 'Type',
        description: 'Description',
        doneAt: 'Date',
        message: 'Info',
        label: 'Name',
        interval: 'Interval',
        category: 'Category',
        amount: 'Amount',
      },
    },
  },
} satisfies Record<Sprache, typeof de>
