import type { Sprache } from '../../lib/sprache'

// PDF-Berichte (services/pdf-report.ts): Dossier eines Fahrzeugs, Serviceheft für den Käufer, Fuhrpark-Übersicht.
// jsPDF-Standardschrift (WinAnsi): Akzente, « » und • gehen, andere Sonderzeichen nicht.
const de = {
  feld: {
    kontrollschild: 'Kennzeichen',
    baujahr: 'Baujahr',
    fahrgestellnummer: 'Fahrgestellnummer',
    kilometerstand: 'Kilometerstand',
    verkauft: 'Verkauft',
  },
  verkauftBei: (datum: string, km: string) => `${datum} bei ${km} km`,
  uebergabeAm: (datum: string) => `Übergabe am ${datum}`,
  wartungshistorie: 'Wartungshistorie',
  datum: 'Datum',
  arbeit: 'Arbeit',
  keineEintraege: 'Keine Einträge',
  kostenProJahr: 'Kosten pro Jahr',
  jahr: 'Jahr',
  waehrung: 'Währung',
  total: 'Total',
  keineRechnungen: 'Keine Rechnungen',
  umgerechnet: (anzahl: number, waehrung: string) => `${anzahl} Rechnung(en) in fremder Währung zum EZB-Kurs am Rechnungsdatum in ${waehrung} umgerechnet.`,
  rechnungen: 'Rechnungen',
  werkstatt: 'Werkstatt',
  kategorien: 'Kategorien',
  betrag: 'Betrag',
  fuss: (seite: number, von: number) => `wartungsheft.ch · Seite ${seite} von ${von}`,
  serviceheft: (fahrzeug: string) => `Serviceheft ${fahrzeug}`,
  stand: (datum: string) => `Stand ${datum}`,
  eintraege: 'Einträge',
  eintraegeWert: (anzahl: number, von: string, bis: string) => `${anzahl} von ${von} bis ${bis}`,
  keine: 'keine',
  laufleistung: 'Belegte Laufleistung',
  vonBis: (von: string, bis: string) => `${von} bis ${bis}`,
  historie: 'Historie',
  lueckenlos: 'lückenlos dokumentiert',
  mitLuecken: (hinweis: string) => `mit Lücken (${hinweis})`,
  belege: 'Belege',
  belegeWert: (mitFoto: number, alle: number) => `${mitFoto} von ${alle} Rechnungen mit Foto`,
  belegFehlt: 'Beleg konnte nicht eingebettet werden.',
  gefuehrt: 'Geführt mit Wartungsheft',
  vorteile: [
    'Werkstattrechnung fotografieren, die KI liest Werkstatt, Datum, Betrag und Positionen heraus.',
    'Fälligkeiten für Service, Bremsen, Reifen und MFK, mit E-Mail-Erinnerung.',
    'Kosten pro Fahrzeug und Jahr, Export für den Treuhänder.',
    'Dieses Serviceheft als PDF, jederzeit neu erstellt.',
    'Daten auf Servern in der Schweiz, KI-Verarbeitung in der EU.',
  ],
  dossierStand: (datum: string) => `Wartungsheft, Stand ${datum}`,
  fuhrpark: 'Fuhrpark-Übersicht',
  fuhrparkUnter: (anzahl: number, datum: string) => `Wartungsheft, ${anzahl} Fahrzeuge, Stand ${datum}`,
  kostenProFahrzeug: 'Kosten pro Fahrzeug und Jahr',
  fahrzeug: 'Fahrzeug',
  gesamt: 'Gesamt',
  fuhrparkUmgerechnet: (waehrung: string) => `Rechnungen in fremder Währung zum EZB-Kurs am Rechnungsdatum in ${waehrung} umgerechnet; ohne Kurs in eigener Währung ausgewiesen.`,
  datei: {
    serviceheft: 'serviceheft',
    alleFahrzeuge: 'alle-fahrzeuge',
  },
}

export default {
  de,
  fr: {
    feld: {
      kontrollschild: 'Plaque',
      baujahr: 'Année',
      fahrgestellnummer: 'Numéro de châssis',
      kilometerstand: 'Kilométrage',
      verkauft: 'Vendu',
    },
    verkauftBei: (datum: string, km: string) => `${datum} à ${km} km`,
    uebergabeAm: (datum: string) => `Remise le ${datum}`,
    wartungshistorie: 'Historique d\'entretien',
    datum: 'Date',
    arbeit: 'Travail',
    keineEintraege: 'Aucune entrée',
    kostenProJahr: 'Coûts par année',
    jahr: 'Année',
    waehrung: 'Monnaie',
    total: 'Total',
    keineRechnungen: 'Aucune facture',
    umgerechnet: (anzahl: number, waehrung: string) => `${anzahl} facture(s) en monnaie étrangère convertie(s) en ${waehrung} au cours BCE du jour de la facture.`,
    rechnungen: 'Factures',
    werkstatt: 'Garage',
    kategorien: 'Catégories',
    betrag: 'Montant',
    fuss: (seite: number, von: number) => `wartungsheft.ch · Page ${seite} sur ${von}`,
    serviceheft: (fahrzeug: string) => `Carnet d'entretien ${fahrzeug}`,
    stand: (datum: string) => `État au ${datum}`,
    eintraege: 'Entrées',
    eintraegeWert: (anzahl: number, von: string, bis: string) => `${anzahl} du ${von} au ${bis}`,
    keine: 'aucune',
    laufleistung: 'Kilométrage attesté',
    vonBis: (von: string, bis: string) => `${von} à ${bis}`,
    historie: 'Historique',
    lueckenlos: 'documenté sans lacune',
    mitLuecken: (hinweis: string) => `avec lacunes (${hinweis})`,
    belege: 'Justificatifs',
    belegeWert: (mitFoto: number, alle: number) => `${mitFoto} factures sur ${alle} avec photo`,
    belegFehlt: 'Le justificatif n\'a pas pu être intégré.',
    gefuehrt: 'Tenu avec Wartungsheft',
    vorteile: [
      'Photographier la facture du garage, l\'IA en extrait garage, date, montant et positions.',
      'Échéances pour service, freins, pneus et expertise (MFK), avec rappel par e-mail.',
      'Coûts par véhicule et par année, export pour la fiduciaire.',
      'Ce carnet d\'entretien en PDF, recréé à tout moment.',
      'Données sur des serveurs en Suisse, traitement IA dans l\'UE.',
    ],
    dossierStand: (datum: string) => `Wartungsheft, état au ${datum}`,
    fuhrpark: 'Aperçu de la flotte',
    fuhrparkUnter: (anzahl: number, datum: string) => `Wartungsheft, ${anzahl} véhicules, état au ${datum}`,
    kostenProFahrzeug: 'Coûts par véhicule et par année',
    fahrzeug: 'Véhicule',
    gesamt: 'Total général',
    fuhrparkUmgerechnet: (waehrung: string) => `Factures en monnaie étrangère converties en ${waehrung} au cours BCE du jour de la facture ; sans cours, indiquées dans leur propre monnaie.`,
    datei: {
      serviceheft: 'carnet-entretien',
      alleFahrzeuge: 'tous-les-vehicules',
    },
  },
  it: {
    feld: {
      kontrollschild: 'Targa',
      baujahr: 'Anno',
      fahrgestellnummer: 'Numero di telaio',
      kilometerstand: 'Chilometraggio',
      verkauft: 'Venduto',
    },
    verkauftBei: (datum: string, km: string) => `${datum} a ${km} km`,
    uebergabeAm: (datum: string) => `Consegna il ${datum}`,
    wartungshistorie: 'Storico della manutenzione',
    datum: 'Data',
    arbeit: 'Lavoro',
    keineEintraege: 'Nessuna registrazione',
    kostenProJahr: 'Costi per anno',
    jahr: 'Anno',
    waehrung: 'Valuta',
    total: 'Totale',
    keineRechnungen: 'Nessuna fattura',
    umgerechnet: (anzahl: number, waehrung: string) => `${anzahl} fattura/e in valuta estera convertita/e in ${waehrung} al cambio BCE della data della fattura.`,
    rechnungen: 'Fatture',
    werkstatt: 'Officina',
    kategorien: 'Categorie',
    betrag: 'Importo',
    fuss: (seite: number, von: number) => `wartungsheft.ch · Pagina ${seite} di ${von}`,
    serviceheft: (fahrzeug: string) => `Libretto di manutenzione ${fahrzeug}`,
    stand: (datum: string) => `Aggiornato al ${datum}`,
    eintraege: 'Registrazioni',
    eintraegeWert: (anzahl: number, von: string, bis: string) => `${anzahl} dal ${von} al ${bis}`,
    keine: 'nessuna',
    laufleistung: 'Chilometraggio documentato',
    vonBis: (von: string, bis: string) => `da ${von} a ${bis}`,
    historie: 'Storico',
    lueckenlos: 'documentato senza lacune',
    mitLuecken: (hinweis: string) => `con lacune (${hinweis})`,
    belege: 'Giustificativi',
    belegeWert: (mitFoto: number, alle: number) => `${mitFoto} fatture su ${alle} con foto`,
    belegFehlt: 'Impossibile inserire il giustificativo.',
    gefuehrt: 'Tenuto con Wartungsheft',
    vorteile: [
      'Fotografa la fattura dell\'officina, l\'IA ne legge officina, data, importo e posizioni.',
      'Scadenze per servizio, freni, pneumatici e collaudo (MFK), con promemoria via e-mail.',
      'Costi per veicolo e per anno, esportazione per il fiduciario.',
      'Questo libretto di manutenzione in PDF, rigenerato in ogni momento.',
      'Dati su server in Svizzera, elaborazione IA nell\'UE.',
    ],
    dossierStand: (datum: string) => `Wartungsheft, aggiornato al ${datum}`,
    fuhrpark: 'Panoramica del parco veicoli',
    fuhrparkUnter: (anzahl: number, datum: string) => `Wartungsheft, ${anzahl} veicoli, aggiornato al ${datum}`,
    kostenProFahrzeug: 'Costi per veicolo e per anno',
    fahrzeug: 'Veicolo',
    gesamt: 'Totale complessivo',
    fuhrparkUmgerechnet: (waehrung: string) => `Fatture in valuta estera convertite in ${waehrung} al cambio BCE della data della fattura; senza cambio indicate nella propria valuta.`,
    datei: {
      serviceheft: 'libretto-manutenzione',
      alleFahrzeuge: 'tutti-i-veicoli',
    },
  },
  en: {
    feld: {
      kontrollschild: 'Number plate',
      baujahr: 'Year',
      fahrgestellnummer: 'Chassis number',
      kilometerstand: 'Mileage',
      verkauft: 'Sold',
    },
    verkauftBei: (datum: string, km: string) => `${datum} at ${km} km`,
    uebergabeAm: (datum: string) => `Handover on ${datum}`,
    wartungshistorie: 'Maintenance history',
    datum: 'Date',
    arbeit: 'Work',
    keineEintraege: 'No entries',
    kostenProJahr: 'Costs per year',
    jahr: 'Year',
    waehrung: 'Currency',
    total: 'Total',
    keineRechnungen: 'No invoices',
    umgerechnet: (anzahl: number, waehrung: string) => `${anzahl} invoice(s) in a foreign currency converted to ${waehrung} at the ECB rate on the invoice date.`,
    rechnungen: 'Invoices',
    werkstatt: 'Garage',
    kategorien: 'Categories',
    betrag: 'Amount',
    fuss: (seite: number, von: number) => `wartungsheft.ch · Page ${seite} of ${von}`,
    serviceheft: (fahrzeug: string) => `Service book ${fahrzeug}`,
    stand: (datum: string) => `As of ${datum}`,
    eintraege: 'Entries',
    eintraegeWert: (anzahl: number, von: string, bis: string) => `${anzahl} from ${von} to ${bis}`,
    keine: 'none',
    laufleistung: 'Documented mileage',
    vonBis: (von: string, bis: string) => `${von} to ${bis}`,
    historie: 'History',
    lueckenlos: 'fully documented',
    mitLuecken: (hinweis: string) => `with gaps (${hinweis})`,
    belege: 'Receipts',
    belegeWert: (mitFoto: number, alle: number) => `${mitFoto} of ${alle} invoices with photo`,
    belegFehlt: 'The receipt could not be embedded.',
    gefuehrt: 'Kept with Wartungsheft',
    vorteile: [
      'Photograph the garage invoice, the AI reads garage, date, amount and line items.',
      'Due dates for service, brakes, tyres and vehicle inspection (MFK), with email reminder.',
      'Costs per vehicle and year, export for the accountant.',
      'This service book as a PDF, recreated at any time.',
      'Data on servers in Switzerland, AI processing in the EU.',
    ],
    dossierStand: (datum: string) => `Wartungsheft, as of ${datum}`,
    fuhrpark: 'Fleet overview',
    fuhrparkUnter: (anzahl: number, datum: string) => `Wartungsheft, ${anzahl} vehicles, as of ${datum}`,
    kostenProFahrzeug: 'Costs per vehicle and year',
    fahrzeug: 'Vehicle',
    gesamt: 'Grand total',
    fuhrparkUmgerechnet: (waehrung: string) => `Invoices in a foreign currency converted to ${waehrung} at the ECB rate on the invoice date; without a rate, shown in their own currency.`,
    datei: {
      serviceheft: 'service-book',
      alleFahrzeuge: 'all-vehicles',
    },
  },
} satisfies Record<Sprache, typeof de>
