import type { Sprache } from '../../lib/sprache'

// Einstellungen (pages/SettingsPage.vue)
const de = {
  sprache: {
    titel: 'Sprache',
    label: 'Sprache der App',
    hinweis: 'Gilt für alle Seiten nach der Anmeldung und für die Erinnerungsmails.',
    nurGeraet: 'Sprache nur auf diesem Gerät gespeichert',
  },
  design: {
    titel: 'Design',
    farbschema: 'Farbschema',
    dunkel: 'Dunkel',
    hell: 'Hell',
    system: 'System',
  },
  waehrung: {
    titel: 'Währung',
    heimwaehrung: 'Heimwährung',
    hinweis: 'Kostenübersicht und Exporte rechnen fremde Währungen zum EZB-Kurs am Rechnungsdatum in diese Währung um. Rechnungen behalten ihre Originalwährung.',
  },
  erinnerungen: {
    titel: 'Erinnerungen',
    label: 'Fällige Wartungen per E-Mail',
    hinweis: 'Eine E-Mail an deine Login-Adresse, sobald eine Arbeit bald fällig oder überfällig ist. Unveränderte Erinnerungen höchstens alle 30 Tage.',
    nichtGespeichert: 'Einstellung nicht gespeichert',
  },
  abo: {
    titel: 'Abo & Nutzung',
    aktuellerPlan: 'Aktueller Plan:',
    doppelpunkt: ':',
    testzeit: 'Testzeit',
    planPrivat: 'Privat',
    planBetrieb: 'Betrieb',
    gratis: 'gratis',
    proFahrzeugJahr: (preis: string) => `${preis} pro Fahrzeug und Jahr`,
    proJahr: (preis: string) => `${preis} / Jahr`,
    testzeitLaeuft: (tage: number, datum: string, privat: string, max: number, betrieb: string) => `Testzeit: noch ${tage} ${tage === 1 ? 'Tag' : 'Tage'} mit allen Funktionen, bis ${datum}. Danach kostet Wartungsheft ${privat} im Jahr (privat, bis ${max} Fahrzeuge) oder ${betrieb} pro Fahrzeug und Jahr (Betrieb).`,
    testzeitVorbei: (privat: string, max: number, betrieb: string) => `Testzeit vorbei: KI-Scan und Chat brauchen ein Abo (privat ${privat} im Jahr bis ${max} Fahrzeuge, Betrieb ${betrieb} pro Fahrzeug und Jahr). Lesen, Erfassen von Hand und Exporte gehen weiter.`,
    scans: 'Scans',
    chat: 'Chat',
    genutzt: (prozent: number) => `${prozent} % genutzt`,
    unterEinProzent: 'unter 1 % genutzt',
    zaehler: (monat: string) => `Zähler gelten für ${monat}. KI-Verarbeitung über Mistral (Frankreich, EU) ist im Abo enthalten, kein eigener API-Key nötig.`,
    fairUse: 'Die Schwellen sind Fair Use gegen Missbrauch, kein Sparziel: normaler Gebrauch kommt nie in ihre Nähe.',
    jahresabo: (art: string) => `Jahresabo ${art}`,
    fahrzeuge: (n: number) => `${n} ${n === 1 ? 'Fahrzeug' : 'Fahrzeuge'}`,
    gekuendigtBis: (datum: string) => `Gekündigt, läuft bis ${datum}.`,
    laeuftBis: (datum: string) => `Läuft bis ${datum}, verlängert sich automatisch um ein Jahr.`,
    offeneRechnung: (nummer: string, betrag: string, datum: string) => `Rechnung ${nummer} über ${betrag}, zahlbar bis ${datum}. Die Rechnung kommt per Mail; fehlt sie, schreib an`,
    mailBetreff: (nummer: string) => `Rechnung ${nummer}`,
    kuendigungZuruecknehmen: 'Kündigung zurücknehmen',
    kuendigen: 'Abo kündigen',
    privatZeile: (preis: string, max: number) => `${preis} im Jahr bis ${max} Fahrzeuge.`,
    betriebZeile: (preis: string) => `${preis} pro Fahrzeug und Jahr, Rechnung auf die Firma. Beides zahlbar in 30 Tagen.`,
    frueherBestellen: (datum: string) => `Bestellst du jetzt, beginnt das bezahlte Jahr erst am ${datum} — du verschenkst also keinen Tag der Testzeit.`,
    bestellen: 'Jahresabo bestellen',
    bisFahrzeuge: (n: number) => `bis ${n} Fahrzeuge`,
    rechnungFirma: 'Rechnung auf die Firma',
    ohneLimit: 'Scannen ohne Limit im Alltag',
    wechseln: (plan: string) => `Auf ${plan} wechseln`,
    team: 'Mehrere Fahrer? Mit einer Team-Adresse anmelden (z. B. fuhrpark@deinbetrieb.ch), jedes Handy einmal mit dem Code aus diesem Postfach. Dann fotografiert jeder mit demselben Zugang.',
    bestellt: (nummer: string) => `Jahresabo bestellt, Rechnung ${nummer}`,
    unterwegs: 'Die QR-Rechnung ist per Mail unterwegs.',
    kommtNoch: (mail: string) => `Die Rechnung kommt in den nächsten Tagen per Mail. Fragen an ${mail}.`,
    gekuendigt: 'Abo gekündigt',
    storniert: 'Die Rechnung ist storniert, du musst nichts bezahlen.',
    bisEnde: 'Es läuft bis zum Ende der Laufzeit.',
  },
  daten: {
    titel: 'Daten',
    exportieren: 'Daten exportieren',
    erweitertAus: 'Erweitert ausblenden',
    erweitertAn: 'Erweitert anzeigen',
    importieren: 'Daten importieren',
    cacheLeeren: 'Scan-Zwischenspeicher leeren',
    gespeicherteScans: (n: number) => `${n} gespeicherte Scans`,
    exportiert: 'Daten exportiert',
    importOk: (zusammenfassung: string) => `Import erfolgreich: ${zusammenfassung}`,
    importFehler: (meldung: string) => `Import fehlgeschlagen: ${meldung}`,
    cacheGeleert: 'Scan-Zwischenspeicher geleert',
    arten: {
      vehicles: ['Fahrzeug', 'Fahrzeuge'],
      invoices: ['Rechnung', 'Rechnungen'],
      maintenances: ['Wartung', 'Wartungen'],
      ocrCache: ['Scan', 'Scans'],
      chatmessages: ['Chat-Nachricht', 'Chat-Nachrichten'],
    },
  },
  konto: {
    titel: 'Konto',
    hinweis: 'Deine Daten gehören dir. Löschst du das Konto, sind Fahrzeuge, Rechnungen, Wartungen und Chat sofort weg, und du bist abgemeldet. Vorher lohnt sich «Daten exportieren». Rechnungen, die wir dir gestellt haben, bewahren wir auf, so lange das Gesetz es verlangt.',
    loeschen: 'Konto löschen',
    frage: 'Konto löschen?',
    text: 'Alle Fahrzeuge, Rechnungen und Wartungen werden gelöscht, das Login dazu. Das lässt sich nicht rückgängig machen.',
    endgueltig: 'Endgültig löschen',
    geloescht: 'Konto gelöscht',
    geloeschtDetail: 'Alle Daten sind weg. Danke fürs Ausprobieren.',
    nichtGeloescht: 'Konto nicht gelöscht',
  },
}

export default {
  de,
  fr: {
    sprache: {
      titel: 'Langue',
      label: 'Langue de l\'application',
      hinweis: 'S\'applique à toutes les pages après la connexion et aux e-mails de rappel.',
      nurGeraet: 'Langue enregistrée sur cet appareil seulement',
    },
    design: {
      titel: 'Apparence',
      farbschema: 'Thème de couleurs',
      dunkel: 'Sombre',
      hell: 'Clair',
      system: 'Système',
    },
    waehrung: {
      titel: 'Monnaie',
      heimwaehrung: 'Monnaie de référence',
      hinweis: 'L\'aperçu des coûts et les exports convertissent les monnaies étrangères dans cette monnaie au cours de la BCE à la date de la facture. Les factures gardent leur monnaie d\'origine.',
    },
    erinnerungen: {
      titel: 'Rappels',
      label: 'Entretiens à faire par e-mail',
      hinweis: 'Un e-mail à ton adresse de connexion dès qu\'un travail est bientôt dû ou en retard. Un rappel inchangé au plus tous les 30 jours.',
      nichtGespeichert: 'Réglage non enregistré',
    },
    abo: {
      titel: 'Abonnement et utilisation',
      aktuellerPlan: 'Formule actuelle :',
      doppelpunkt: ' :',
      testzeit: 'Période d\'essai',
      planPrivat: 'Particulier',
      planBetrieb: 'Entreprise',
      gratis: 'gratuit',
      proFahrzeugJahr: (preis: string) => `${preis} par véhicule et par an`,
      proJahr: (preis: string) => `${preis} / an`,
      testzeitLaeuft: (tage: number, datum: string, privat: string, max: number, betrieb: string) => `Période d'essai : encore ${tage} ${tage === 1 ? 'jour' : 'jours'} avec toutes les fonctions, jusqu'au ${datum}. Ensuite, Wartungsheft coûte ${privat} par an (particulier, jusqu'à ${max} véhicules) ou ${betrieb} par véhicule et par an (entreprise).`,
      testzeitVorbei: (privat: string, max: number, betrieb: string) => `Période d'essai terminée : le scan IA et le chat nécessitent un abonnement (particulier ${privat} par an jusqu'à ${max} véhicules, entreprise ${betrieb} par véhicule et par an). La consultation, la saisie manuelle et les exports continuent.`,
      scans: 'Scans',
      chat: 'Chat',
      genutzt: (prozent: number) => `${prozent} % utilisés`,
      unterEinProzent: 'moins de 1 % utilisé',
      zaehler: (monat: string) => `Compteurs valables pour ${monat}. Le traitement IA par Mistral (France, UE) est compris dans l'abonnement, pas besoin de clé API.`,
      fairUse: 'Les seuils sont un usage équitable contre les abus, pas un objectif d\'économie : un usage normal n\'en approche jamais.',
      jahresabo: (art: string) => `Abonnement annuel ${art}`,
      fahrzeuge: (n: number) => `${n} ${n === 1 ? 'véhicule' : 'véhicules'}`,
      gekuendigtBis: (datum: string) => `Résilié, court jusqu'au ${datum}.`,
      laeuftBis: (datum: string) => `Court jusqu'au ${datum}, se renouvelle automatiquement d'un an.`,
      offeneRechnung: (nummer: string, betrag: string, datum: string) => `Facture ${nummer} de ${betrag}, payable jusqu'au ${datum}. La facture arrive par e-mail ; si elle manque, écris à`,
      mailBetreff: (nummer: string) => `Facture ${nummer}`,
      kuendigungZuruecknehmen: 'Annuler la résiliation',
      kuendigen: 'Résilier l\'abonnement',
      privatZeile: (preis: string, max: number) => `${preis} par an jusqu'à ${max} véhicules.`,
      betriebZeile: (preis: string) => `${preis} par véhicule et par an, facture au nom de l'entreprise. Les deux payables à 30 jours.`,
      frueherBestellen: (datum: string) => `Si tu commandes maintenant, l'année payante ne commence que le ${datum} : tu ne perds aucun jour de ta période d'essai.`,
      bestellen: 'Commander l\'abonnement annuel',
      bisFahrzeuge: (n: number) => `jusqu'à ${n} véhicules`,
      rechnungFirma: 'facture au nom de l\'entreprise',
      ohneLimit: 'scans sans limite au quotidien',
      wechseln: (plan: string) => `Passer à ${plan}`,
      team: 'Plusieurs conducteurs ? Connecte-toi avec une adresse d\'équipe (p. ex. flotte@tonentreprise.ch), chaque téléphone une fois avec le code reçu dans cette boîte. Ensuite, chacun photographie avec le même accès.',
      bestellt: (nummer: string) => `Abonnement annuel commandé, facture ${nummer}`,
      unterwegs: 'La facture QR est en route par e-mail.',
      kommtNoch: (mail: string) => `La facture arrive dans les prochains jours par e-mail. Questions à ${mail}.`,
      gekuendigt: 'Abonnement résilié',
      storniert: 'La facture est annulée, tu n\'as rien à payer.',
      bisEnde: 'Il court jusqu\'à la fin de la période.',
    },
    daten: {
      titel: 'Données',
      exportieren: 'Exporter les données',
      erweitertAus: 'Masquer les options avancées',
      erweitertAn: 'Options avancées',
      importieren: 'Importer des données',
      cacheLeeren: 'Vider la mémoire des scans',
      gespeicherteScans: (n: number) => `${n} scans enregistrés`,
      exportiert: 'Données exportées',
      importOk: (zusammenfassung: string) => `Import réussi : ${zusammenfassung}`,
      importFehler: (meldung: string) => `Échec de l'import : ${meldung}`,
      cacheGeleert: 'Mémoire des scans vidée',
      arten: {
        vehicles: ['véhicule', 'véhicules'],
        invoices: ['facture', 'factures'],
        maintenances: ['entretien', 'entretiens'],
        ocrCache: ['scan', 'scans'],
        chatmessages: ['message de chat', 'messages de chat'],
      },
    },
    konto: {
      titel: 'Compte',
      hinweis: 'Tes données t\'appartiennent. Si tu supprimes le compte, les véhicules, factures, entretiens et le chat disparaissent immédiatement et tu es déconnecté. Avant, mieux vaut utiliser « Exporter les données ». Les factures que nous t\'avons adressées sont conservées aussi longtemps que la loi l\'exige.',
      loeschen: 'Supprimer le compte',
      frage: 'Supprimer le compte ?',
      text: 'Tous les véhicules, factures et entretiens seront supprimés, ainsi que l\'accès. C\'est irréversible.',
      endgueltig: 'Supprimer définitivement',
      geloescht: 'Compte supprimé',
      geloeschtDetail: 'Toutes les données ont disparu. Merci d\'avoir essayé.',
      nichtGeloescht: 'Compte non supprimé',
    },
  },
  it: {
    sprache: {
      titel: 'Lingua',
      label: 'Lingua dell\'app',
      hinweis: 'Vale per tutte le pagine dopo l\'accesso e per le e-mail di promemoria.',
      nurGeraet: 'Lingua salvata solo su questo dispositivo',
    },
    design: {
      titel: 'Aspetto',
      farbschema: 'Tema colori',
      dunkel: 'Scuro',
      hell: 'Chiaro',
      system: 'Sistema',
    },
    waehrung: {
      titel: 'Valuta',
      heimwaehrung: 'Valuta di riferimento',
      hinweis: 'La panoramica dei costi e le esportazioni convertono le valute estere in questa valuta al cambio BCE alla data della fattura. Le fatture mantengono la loro valuta originale.',
    },
    erinnerungen: {
      titel: 'Promemoria',
      label: 'Manutenzioni in scadenza via e-mail',
      hinweis: 'Un\'e-mail al tuo indirizzo di accesso appena un lavoro è in scadenza o scaduto. Promemoria invariati al massimo ogni 30 giorni.',
      nichtGespeichert: 'Impostazione non salvata',
    },
    abo: {
      titel: 'Abbonamento e utilizzo',
      aktuellerPlan: 'Piano attuale:',
      doppelpunkt: ':',
      testzeit: 'Periodo di prova',
      planPrivat: 'Privato',
      planBetrieb: 'Azienda',
      gratis: 'gratuito',
      proFahrzeugJahr: (preis: string) => `${preis} per veicolo e anno`,
      proJahr: (preis: string) => `${preis} / anno`,
      testzeitLaeuft: (tage: number, datum: string, privat: string, max: number, betrieb: string) => `Periodo di prova: ancora ${tage} ${tage === 1 ? 'giorno' : 'giorni'} con tutte le funzioni, fino al ${datum}. Dopo, Wartungsheft costa ${privat} all'anno (privati, fino a ${max} veicoli) o ${betrieb} per veicolo e anno (aziende).`,
      testzeitVorbei: (privat: string, max: number, betrieb: string) => `Periodo di prova terminato: scansione IA e chat richiedono un abbonamento (privati ${privat} all'anno fino a ${max} veicoli, aziende ${betrieb} per veicolo e anno). Lettura, registrazione manuale ed esportazioni continuano.`,
      scans: 'Scansioni',
      chat: 'Chat',
      genutzt: (prozent: number) => `${prozent} % utilizzato`,
      unterEinProzent: 'meno dell\'1 % utilizzato',
      zaehler: (monat: string) => `Contatori validi per ${monat}. L'elaborazione IA tramite Mistral (Francia, UE) è compresa nell'abbonamento, non serve una chiave API propria.`,
      fairUse: 'Le soglie sono un uso equo contro gli abusi, non un obiettivo di risparmio: un uso normale non ci si avvicina mai.',
      jahresabo: (art: string) => `Abbonamento annuale ${art}`,
      fahrzeuge: (n: number) => `${n} ${n === 1 ? 'veicolo' : 'veicoli'}`,
      gekuendigtBis: (datum: string) => `Disdetto, valido fino al ${datum}.`,
      laeuftBis: (datum: string) => `Valido fino al ${datum}, si rinnova automaticamente di un anno.`,
      offeneRechnung: (nummer: string, betrag: string, datum: string) => `Fattura ${nummer} di ${betrag}, pagabile entro il ${datum}. La fattura arriva per e-mail; se manca, scrivi a`,
      mailBetreff: (nummer: string) => `Fattura ${nummer}`,
      kuendigungZuruecknehmen: 'Revoca la disdetta',
      kuendigen: 'Disdici l\'abbonamento',
      privatZeile: (preis: string, max: number) => `${preis} all'anno fino a ${max} veicoli.`,
      betriebZeile: (preis: string) => `${preis} per veicolo e anno, fattura intestata alla ditta. Entrambi pagabili entro 30 giorni.`,
      frueherBestellen: (datum: string) => `Se ordini ora, l'anno a pagamento inizia solo il ${datum}: non perdi nessun giorno del periodo di prova.`,
      bestellen: 'Ordina l\'abbonamento annuale',
      bisFahrzeuge: (n: number) => `fino a ${n} veicoli`,
      rechnungFirma: 'fattura intestata alla ditta',
      ohneLimit: 'scansioni senza limiti nell\'uso quotidiano',
      wechseln: (plan: string) => `Passa a ${plan}`,
      team: 'Più conducenti? Accedi con un indirizzo di squadra (p. es. flotta@tuaazienda.ch), ogni telefono una volta con il codice di quella casella. Poi ognuno fotografa con lo stesso accesso.',
      bestellt: (nummer: string) => `Abbonamento annuale ordinato, fattura ${nummer}`,
      unterwegs: 'La fattura QR è in arrivo per e-mail.',
      kommtNoch: (mail: string) => `La fattura arriva nei prossimi giorni per e-mail. Domande a ${mail}.`,
      gekuendigt: 'Abbonamento disdetto',
      storniert: 'La fattura è annullata, non devi pagare nulla.',
      bisEnde: 'Resta valido fino alla fine del periodo.',
    },
    daten: {
      titel: 'Dati',
      exportieren: 'Esporta i dati',
      erweitertAus: 'Nascondi opzioni avanzate',
      erweitertAn: 'Opzioni avanzate',
      importieren: 'Importa dati',
      cacheLeeren: 'Svuota la memoria delle scansioni',
      gespeicherteScans: (n: number) => `${n} scansioni salvate`,
      exportiert: 'Dati esportati',
      importOk: (zusammenfassung: string) => `Importazione riuscita: ${zusammenfassung}`,
      importFehler: (meldung: string) => `Importazione non riuscita: ${meldung}`,
      cacheGeleert: 'Memoria delle scansioni svuotata',
      arten: {
        vehicles: ['veicolo', 'veicoli'],
        invoices: ['fattura', 'fatture'],
        maintenances: ['manutenzione', 'manutenzioni'],
        ocrCache: ['scansione', 'scansioni'],
        chatmessages: ['messaggio chat', 'messaggi chat'],
      },
    },
    konto: {
      titel: 'Account',
      hinweis: 'I tuoi dati ti appartengono. Se elimini l\'account, veicoli, fatture, manutenzioni e chat spariscono subito e vieni disconnesso. Prima conviene usare «Esporta i dati». Le fatture che ti abbiamo emesso le conserviamo per il tempo previsto dalla legge.',
      loeschen: 'Elimina account',
      frage: 'Eliminare l\'account?',
      text: 'Tutti i veicoli, le fatture e le manutenzioni vengono eliminati, insieme all\'accesso. Non si può annullare.',
      endgueltig: 'Elimina definitivamente',
      geloescht: 'Account eliminato',
      geloeschtDetail: 'Tutti i dati sono stati eliminati. Grazie per aver provato.',
      nichtGeloescht: 'Account non eliminato',
    },
  },
  en: {
    sprache: {
      titel: 'Language',
      label: 'App language',
      hinweis: 'Applies to all pages after signing in and to reminder emails.',
      nurGeraet: 'Language saved on this device only',
    },
    design: {
      titel: 'Appearance',
      farbschema: 'Colour scheme',
      dunkel: 'Dark',
      hell: 'Light',
      system: 'System',
    },
    waehrung: {
      titel: 'Currency',
      heimwaehrung: 'Home currency',
      hinweis: 'The cost overview and exports convert foreign currencies into this currency at the ECB rate on the invoice date. Invoices keep their original currency.',
    },
    erinnerungen: {
      titel: 'Reminders',
      label: 'Due maintenance by email',
      hinweis: 'An email to your sign-in address as soon as a job is due soon or overdue. Unchanged reminders at most every 30 days.',
      nichtGespeichert: 'Setting not saved',
    },
    abo: {
      titel: 'Subscription & usage',
      aktuellerPlan: 'Current plan:',
      doppelpunkt: ':',
      testzeit: 'Trial',
      planPrivat: 'Private',
      planBetrieb: 'Business',
      gratis: 'free',
      proFahrzeugJahr: (preis: string) => `${preis} per vehicle and year`,
      proJahr: (preis: string) => `${preis} / year`,
      testzeitLaeuft: (tage: number, datum: string, privat: string, max: number, betrieb: string) => `Trial: ${tage} more ${tage === 1 ? 'day' : 'days'} with all features, until ${datum}. After that, Wartungsheft costs ${privat} a year (private, up to ${max} vehicles) or ${betrieb} per vehicle and year (business).`,
      testzeitVorbei: (privat: string, max: number, betrieb: string) => `Trial over: AI scan and chat need a subscription (private ${privat} a year up to ${max} vehicles, business ${betrieb} per vehicle and year). Reading, manual entry and exports carry on.`,
      scans: 'Scans',
      chat: 'Chat',
      genutzt: (prozent: number) => `${prozent} % used`,
      unterEinProzent: 'under 1 % used',
      zaehler: (monat: string) => `Counters apply to ${monat}. AI processing via Mistral (France, EU) is included in the subscription, no API key of your own needed.`,
      fairUse: 'The thresholds are fair use against abuse, not a savings target: normal use never comes close.',
      jahresabo: (art: string) => `Annual subscription ${art}`,
      fahrzeuge: (n: number) => `${n} ${n === 1 ? 'vehicle' : 'vehicles'}`,
      gekuendigtBis: (datum: string) => `Cancelled, runs until ${datum}.`,
      laeuftBis: (datum: string) => `Runs until ${datum}, renews automatically for one year.`,
      offeneRechnung: (nummer: string, betrag: string, datum: string) => `Invoice ${nummer} for ${betrag}, payable by ${datum}. The invoice comes by email; if it is missing, write to`,
      mailBetreff: (nummer: string) => `Invoice ${nummer}`,
      kuendigungZuruecknehmen: 'Withdraw cancellation',
      kuendigen: 'Cancel subscription',
      privatZeile: (preis: string, max: number) => `${preis} a year for up to ${max} vehicles.`,
      betriebZeile: (preis: string) => `${preis} per vehicle and year, invoiced to the company. Both payable within 30 days.`,
      frueherBestellen: (datum: string) => `If you order now, the paid year only starts on ${datum}, so you don't lose a single day of your trial.`,
      bestellen: 'Order annual subscription',
      bisFahrzeuge: (n: number) => `up to ${n} vehicles`,
      rechnungFirma: 'invoiced to the company',
      ohneLimit: 'unlimited scanning in everyday use',
      wechseln: (plan: string) => `Switch to ${plan}`,
      team: 'Several drivers? Sign in with a team address (e.g. fleet@yourcompany.ch), each phone once with the code from that mailbox. Then everyone takes photos with the same access.',
      bestellt: (nummer: string) => `Annual subscription ordered, invoice ${nummer}`,
      unterwegs: 'The QR invoice is on its way by email.',
      kommtNoch: (mail: string) => `The invoice will arrive by email in the next few days. Questions to ${mail}.`,
      gekuendigt: 'Subscription cancelled',
      storniert: 'The invoice has been cancelled, you don\'t have to pay anything.',
      bisEnde: 'It runs until the end of the term.',
    },
    daten: {
      titel: 'Data',
      exportieren: 'Export data',
      erweitertAus: 'Hide advanced',
      erweitertAn: 'Show advanced',
      importieren: 'Import data',
      cacheLeeren: 'Clear scan cache',
      gespeicherteScans: (n: number) => `${n} stored scans`,
      exportiert: 'Data exported',
      importOk: (zusammenfassung: string) => `Import successful: ${zusammenfassung}`,
      importFehler: (meldung: string) => `Import failed: ${meldung}`,
      cacheGeleert: 'Scan cache cleared',
      arten: {
        vehicles: ['vehicle', 'vehicles'],
        invoices: ['invoice', 'invoices'],
        maintenances: ['maintenance record', 'maintenance records'],
        ocrCache: ['scan', 'scans'],
        chatmessages: ['chat message', 'chat messages'],
      },
    },
    konto: {
      titel: 'Account',
      hinweis: 'Your data belongs to you. If you delete the account, vehicles, invoices, maintenance records and chat are gone immediately and you are signed out. Use “Export data” first. Invoices we have issued to you are kept for as long as the law requires.',
      loeschen: 'Delete account',
      frage: 'Delete account?',
      text: 'All vehicles, invoices and maintenance records will be deleted, along with the sign-in. This cannot be undone.',
      endgueltig: 'Delete permanently',
      geloescht: 'Account deleted',
      geloeschtDetail: 'All data is gone. Thanks for trying it out.',
      nichtGeloescht: 'Account not deleted',
    },
  },
} satisfies Record<Sprache, typeof de>
