import type { Sprache } from '../../lib/sprache'

// Formular «Neues Fahrzeug» und Bearbeiten (VehicleForm.vue), Ausweis-Scan (composables/useVehicleScan.ts)
const de = {
  ausweisFotografieren: 'Fahrzeugausweis fotografieren',
  wirdGelesen: 'Dokument wird gelesen …',
  scanHinweis: 'Füllt Marke, Modell, Jahr, Kontrollschild und Fahrgestellnummer aus. Kaufvertrag geht auch.',
  dokument: 'Dokument',
  marke: 'Marke',
  modell: 'Modell',
  baujahr: 'Baujahr',
  kilometerstand: 'Kilometerstand',
  kontrollschild: 'Kontrollschild',
  fahrgestellnummer: 'Fahrgestellnummer',
  speichern: 'Speichern',
  scan: {
    nurFotoPdf: 'Nur Fotos oder PDF möglich.',
    zuGross: (mb: number) => `Datei zu gross (max. ${mb} MB).`,
    ausgefuellt: 'Felder aus dem Dokument ausgefüllt. Bitte prüfen.',
    nichtsGefunden: 'Im Dokument waren keine Fahrzeugdaten zu lesen. Bitte Felder selbst ausfüllen.',
    selbstAusfuellen: (fehler: string) => `${fehler} Felder bitte selbst ausfüllen.`,
  },
}

export default {
  de,
  fr: {
    ausweisFotografieren: 'Photographier le permis de circulation',
    wirdGelesen: 'Lecture du document …',
    scanHinweis: 'Remplit la marque, le modèle, l’année, la plaque et le numéro de châssis. Un contrat de vente fonctionne aussi.',
    dokument: 'Document',
    marke: 'Marque',
    modell: 'Modèle',
    baujahr: 'Année',
    kilometerstand: 'Kilométrage',
    kontrollschild: 'Plaque',
    fahrgestellnummer: 'Numéro de châssis',
    speichern: 'Enregistrer',
    scan: {
      nurFotoPdf: 'Seulement des photos ou des PDF.',
      zuGross: (mb: number) => `Fichier trop volumineux (max. ${mb} Mo).`,
      ausgefuellt: 'Champs remplis depuis le document. Vérifie-les.',
      nichtsGefunden: 'Aucune donnée de véhicule lisible dans le document. Remplis les champs toi-même.',
      selbstAusfuellen: (fehler: string) => `${fehler} Remplis les champs toi-même.`,
    },
  },
  it: {
    ausweisFotografieren: 'Fotografa la licenza di circolazione',
    wirdGelesen: 'Lettura del documento …',
    scanHinweis: 'Compila marca, modello, anno, targa e numero di telaio. Va bene anche un contratto di compravendita.',
    dokument: 'Documento',
    marke: 'Marca',
    modell: 'Modello',
    baujahr: 'Anno',
    kilometerstand: 'Chilometraggio',
    kontrollschild: 'Targa',
    fahrgestellnummer: 'Numero di telaio',
    speichern: 'Salva',
    scan: {
      nurFotoPdf: 'Solo foto o PDF.',
      zuGross: (mb: number) => `File troppo grande (max. ${mb} MB).`,
      ausgefuellt: 'Campi compilati dal documento. Controllali.',
      nichtsGefunden: 'Nel documento non c\'erano dati del veicolo leggibili. Compila tu i campi.',
      selbstAusfuellen: (fehler: string) => `${fehler} Compila tu i campi.`,
    },
  },
  en: {
    ausweisFotografieren: 'Photograph the registration document',
    wirdGelesen: 'Reading document …',
    scanHinweis: 'Fills in make, model, year, number plate and chassis number. A purchase contract works too.',
    dokument: 'Document',
    marke: 'Make',
    modell: 'Model',
    baujahr: 'Year',
    kilometerstand: 'Mileage',
    kontrollschild: 'Number plate',
    fahrgestellnummer: 'Chassis number',
    speichern: 'Save',
    scan: {
      nurFotoPdf: 'Only photos or PDF.',
      zuGross: (mb: number) => `File too large (max. ${mb} MB).`,
      ausgefuellt: 'Fields filled in from the document. Please check them.',
      nichtsGefunden: 'No vehicle data could be read from the document. Please fill in the fields yourself.',
      selbstAusfuellen: (fehler: string) => `${fehler} Please fill in the fields yourself.`,
    },
  },
} satisfies Record<Sprache, typeof de>
