import type { Sprache } from '../../lib/sprache'

// Fahrzeugseite (pages/VehicleDetailPage.vue): Wartungsplan, Verlauf, Rechnungen, Kosten und Dialoge.
// Gemeinsame Knöpfe (Speichern, Abbrechen, Löschen, Bearbeiten) stehen in allgemein.ts.
const de = {
  verkauftEintragen: 'Verkauft eintragen',
  verkauftHinweis: (vermerk: string) => `${vermerk}. Kosten und Rechnungen bleiben erhalten.`,
  dochBehalten: 'Doch behalten',
  kmAendern: 'Kilometerstand ändern',
  tabs: {
    plan: 'Wartungsplan',
    verlauf: 'Verlauf',
    rechnungen: 'Rechnungen',
    kosten: 'Kosten',
  },
  plan: {
    ausServiceheft: 'Intervalle aus dem Serviceheft',
    intervalleBearbeiten: 'Intervalle bearbeiten',
    zuruecksetzen: 'Zurücksetzen',
    allgemein: 'Termine nach allgemeinen Intervallen. Mit dem Serviceheft stimmen sie für genau dieses Fahrzeug, die Stempel werden gleich als Wartungen erfasst.',
    serviceheftFotografieren: 'Serviceheft fotografieren',
    monate: (n: number) => `${n} Monate`,
    zuletzt: 'Zuletzt:',
    beiKm: (km: string) => `bei ${km} km`,
    eintragen: 'Eintragen',
    eintragenTitel: (arbeit: string) => `${arbeit} eintragen`,
  },
  verlauf: {
    wartungHinzufuegen: 'Wartung hinzufügen',
    geplant: 'Geplant',
    terminAm: (datum: string) => `Termin am ${datum}`,
    eintragBearbeiten: 'Eintrag bearbeiten',
    eintragLoeschen: 'Eintrag löschen',
    leer: 'Noch keine Wartungen erfasst. Wann was zuletzt gemacht wurde, trägst du im Wartungsplan ein.',
  },
  rechnungen: {
    hinzufuegen: 'Rechnung hinzufügen',
    ohneWerkstatt: 'Ohne Werkstatt',
    scanAusstehend: 'Scan ausstehend',
    leer: 'Keine Rechnungen. Über «Rechnung hinzufügen» Foto oder PDF der Werkstattrechnung hochladen, die KI füllt das Formular aus.',
  },
  kosten: {
    csvTipp: 'Alle Rechnungspositionen als Tabelle für Excel',
    csv: 'CSV für Excel',
    pdfTipp: 'Stammdaten, Wartungen, Kosten und Rechnungen, für dich und den Treuhänder',
    pdf: 'Kostenbericht (PDF)',
    serviceheftTipp: 'Auszug, Wartungshistorie und Rechnungen als Mappe für den Käufer',
    serviceheft: 'Serviceheft für den Verkauf',
    mitPreisen: 'mit Preisen',
    tabelle: 'Kosten pro Jahr',
    kategorie: 'Kategorie',
    total: 'Total',
    umgerechnet: (n: number, waehrung: string) => `${n} ${n === 1 ? 'Rechnung' : 'Rechnungen'} in fremder Währung, zum EZB-Kurs am Rechnungsdatum in ${waehrung} umgerechnet.`,
    ohneKurs: (n: number) => `${n} ${n === 1 ? 'Rechnung' : 'Rechnungen'} in fremder Währung ohne Kurs, in eigener Spalte ausgewiesen.`,
    leer: 'Noch keine Rechnungen erfasst, darum keine Kosten. Das PDF-Dossier geht trotzdem, mit Stammdaten und Wartungen.',
  },
  rechnung: {
    titel: 'Rechnung',
    vergroessern: 'Klick zum Vergrössern',
    positionen: 'Positionen',
    bearbeiten: 'Rechnung bearbeiten',
    werkstatt: 'Werkstatt',
    datum: 'Datum',
    gesamtbetrag: 'Gesamtbetrag',
    waehrung: 'Währung',
    kilometerstand: 'Kilometerstand',
    beschreibung: 'Beschreibung',
    kategorie: 'Kategorie',
    betrag: 'Betrag',
    positionEntfernen: 'Position entfernen',
    positionHinzufuegen: 'Position hinzufügen',
  },
  wartung: {
    bearbeiten: 'Wartungseintrag bearbeiten',
    typ: 'Typ',
    beschreibung: 'Beschreibung',
    erledigtAm: 'Erledigt am',
    kilometerstand: 'Kilometerstand',
    naechsterTermin: 'Nächster Termin',
    naechsterKm: 'Nächster Kilometerstand',
    status: 'Status',
    erledigt: 'Erledigt',
    faellig: 'Fällig',
    ueberfaellig: 'Überfällig',
  },
  fahrzeugBearbeiten: 'Fahrzeug bearbeiten',
  neueRechnung: 'Neue Rechnung',
  neueWartung: 'Neue Wartung',
  loeschen: {
    rechnung: 'Rechnung löschen?',
    wartung: 'Wartungseintrag löschen?',
    endgueltig: 'Diese Aktion kann nicht rückgängig gemacht werden.',
    plan: 'Wartungsplan zurücksetzen?',
    planText: 'Der fahrzeugspezifische Wartungsplan wird gelöscht und die Standard-Intervalle werden verwendet.',
    fahrzeug: 'Fahrzeug löschen?',
    fahrzeugText: 'Alle Rechnungen und Wartungseinträge werden ebenfalls gelöscht.',
    fahrzeugHinweis: 'Verkauft? Dann besser «Verkauft eintragen»: Das Fahrzeug verschwindet aus den Fälligkeiten, Kosten und Rechnungen bleiben für den Jahresabschluss erhalten.',
  },
}

export default {
  de,
  fr: {
    verkauftEintragen: 'Marquer comme vendu',
    verkauftHinweis: (vermerk: string) => `${vermerk}. Les coûts et les factures sont conservés.`,
    dochBehalten: 'Finalement le garder',
    kmAendern: 'Modifier le kilométrage',
    tabs: {
      plan: 'Plan',
      verlauf: 'Historique',
      rechnungen: 'Factures',
      kosten: 'Coûts',
    },
    plan: {
      ausServiceheft: 'Intervalles du carnet d\'entretien',
      intervalleBearbeiten: 'Modifier les intervalles',
      zuruecksetzen: 'Réinitialiser',
      allgemein: 'Échéances selon des intervalles généraux. Avec le carnet d\'entretien, elles correspondent exactement à ce véhicule, et les tampons sont saisis directement comme entretiens.',
      serviceheftFotografieren: 'Photographier le carnet d\'entretien',
      monate: (n: number) => `${n} mois`,
      zuletzt: 'Dernier :',
      beiKm: (km: string) => `à ${km} km`,
      eintragen: 'Saisir',
      eintragenTitel: (arbeit: string) => `Saisir : ${arbeit}`,
    },
    verlauf: {
      wartungHinzufuegen: 'Ajouter un entretien',
      geplant: 'Planifié',
      terminAm: (datum: string) => `Rendez-vous le ${datum}`,
      eintragBearbeiten: 'Modifier l\'entrée',
      eintragLoeschen: 'Supprimer l\'entrée',
      leer: 'Aucun entretien saisi pour l\'instant. Tu indiques dans le plan d\'entretien quand chaque travail a été fait la dernière fois.',
    },
    rechnungen: {
      hinzufuegen: 'Ajouter une facture',
      ohneWerkstatt: 'Sans garage',
      scanAusstehend: 'Scan en attente',
      leer: 'Aucune facture. Avec « Ajouter une facture », télécharge une photo ou le PDF de la facture du garage, l\'IA remplit le formulaire.',
    },
    kosten: {
      csvTipp: 'Toutes les lignes des factures sous forme de tableau pour Excel',
      csv: 'CSV pour Excel',
      pdfTipp: 'Données du véhicule, entretiens, coûts et factures, pour toi et ta fiduciaire',
      pdf: 'Rapport de coûts (PDF)',
      serviceheftTipp: 'Extrait, historique d\'entretien et factures, en dossier pour l\'acheteur',
      serviceheft: 'Carnet d\'entretien pour la vente',
      mitPreisen: 'avec les prix',
      tabelle: 'Coûts par année',
      kategorie: 'Catégorie',
      total: 'Total',
      umgerechnet: (n: number, waehrung: string) => `${n} ${n === 1 ? 'facture' : 'factures'} en monnaie étrangère, ${n === 1 ? 'convertie' : 'converties'} en ${waehrung} au cours BCE du jour de la facture.`,
      ohneKurs: (n: number) => `${n} ${n === 1 ? 'facture' : 'factures'} en monnaie étrangère sans cours, dans une colonne séparée.`,
      leer: 'Aucune facture saisie pour l\'instant, donc pas de coûts. Le dossier PDF fonctionne quand même, avec les données du véhicule et les entretiens.',
    },
    rechnung: {
      titel: 'Facture',
      vergroessern: 'Clique pour agrandir',
      positionen: 'Lignes',
      bearbeiten: 'Modifier la facture',
      werkstatt: 'Garage',
      datum: 'Date',
      gesamtbetrag: 'Montant total',
      waehrung: 'Monnaie',
      kilometerstand: 'Kilométrage',
      beschreibung: 'Description',
      kategorie: 'Catégorie',
      betrag: 'Montant',
      positionEntfernen: 'Retirer la ligne',
      positionHinzufuegen: 'Ajouter une ligne',
    },
    wartung: {
      bearbeiten: 'Modifier l\'entretien',
      typ: 'Type',
      beschreibung: 'Description',
      erledigtAm: 'Fait le',
      kilometerstand: 'Kilométrage',
      naechsterTermin: 'Prochaine échéance',
      naechsterKm: 'Prochain kilométrage',
      status: 'Statut',
      erledigt: 'Fait',
      faellig: 'À faire',
      ueberfaellig: 'En retard',
    },
    fahrzeugBearbeiten: 'Modifier le véhicule',
    neueRechnung: 'Nouvelle facture',
    neueWartung: 'Nouvel entretien',
    loeschen: {
      rechnung: 'Supprimer la facture ?',
      wartung: 'Supprimer l\'entretien ?',
      endgueltig: 'Cette action est irréversible.',
      plan: 'Réinitialiser le plan d\'entretien ?',
      planText: 'Le plan d\'entretien propre à ce véhicule est supprimé et les intervalles standard sont utilisés.',
      fahrzeug: 'Supprimer le véhicule ?',
      fahrzeugText: 'Toutes les factures et tous les entretiens sont également supprimés.',
      fahrzeugHinweis: 'Vendu ? Alors mieux vaut « Marquer comme vendu » : le véhicule disparaît des échéances, les coûts et les factures restent pour le bouclement annuel.',
    },
  },
  it: {
    verkauftEintragen: 'Segna come venduto',
    verkauftHinweis: (vermerk: string) => `${vermerk}. Costi e fatture restano conservati.`,
    dochBehalten: 'Tienilo comunque',
    kmAendern: 'Modifica chilometraggio',
    tabs: {
      plan: 'Piano',
      verlauf: 'Cronologia',
      rechnungen: 'Fatture',
      kosten: 'Costi',
    },
    plan: {
      ausServiceheft: 'Intervalli dal libretto di manutenzione',
      intervalleBearbeiten: 'Modifica intervalli',
      zuruecksetzen: 'Ripristina',
      allgemein: 'Scadenze secondo intervalli generali. Con il libretto di manutenzione valgono proprio per questo veicolo, e i timbri vengono registrati subito come manutenzioni.',
      serviceheftFotografieren: 'Fotografa il libretto di manutenzione',
      monate: (n: number) => `${n} mesi`,
      zuletzt: 'Ultima volta:',
      beiKm: (km: string) => `a ${km} km`,
      eintragen: 'Registra',
      eintragenTitel: (arbeit: string) => `Registra: ${arbeit}`,
    },
    verlauf: {
      wartungHinzufuegen: 'Aggiungi manutenzione',
      geplant: 'Pianificato',
      terminAm: (datum: string) => `Appuntamento il ${datum}`,
      eintragBearbeiten: 'Modifica voce',
      eintragLoeschen: 'Elimina voce',
      leer: 'Nessuna manutenzione registrata finora. Quando è stato fatto cosa l\'ultima volta lo inserisci nel piano di manutenzione.',
    },
    rechnungen: {
      hinzufuegen: 'Aggiungi fattura',
      ohneWerkstatt: 'Senza officina',
      scanAusstehend: 'Scansione in sospeso',
      leer: 'Nessuna fattura. Con «Aggiungi fattura» carica la foto o il PDF della fattura dell\'officina, l\'IA compila il modulo.',
    },
    kosten: {
      csvTipp: 'Tutte le voci delle fatture come tabella per Excel',
      csv: 'CSV per Excel',
      pdfTipp: 'Dati del veicolo, manutenzioni, costi e fatture, per te e per la fiduciaria',
      pdf: 'Rapporto costi (PDF)',
      serviceheftTipp: 'Estratto, cronologia delle manutenzioni e fatture come cartella per l\'acquirente',
      serviceheft: 'Libretto per la vendita',
      mitPreisen: 'con i prezzi',
      tabelle: 'Costi per anno',
      kategorie: 'Categoria',
      total: 'Totale',
      umgerechnet: (n: number, waehrung: string) => `${n} ${n === 1 ? 'fattura' : 'fatture'} in valuta estera, ${n === 1 ? 'convertita' : 'convertite'} in ${waehrung} al cambio BCE della data della fattura.`,
      ohneKurs: (n: number) => `${n} ${n === 1 ? 'fattura' : 'fatture'} in valuta estera senza cambio, in una colonna a parte.`,
      leer: 'Nessuna fattura registrata finora, quindi nessun costo. Il dossier PDF funziona comunque, con dati del veicolo e manutenzioni.',
    },
    rechnung: {
      titel: 'Fattura',
      vergroessern: 'Clicca per ingrandire',
      positionen: 'Voci',
      bearbeiten: 'Modifica fattura',
      werkstatt: 'Officina',
      datum: 'Data',
      gesamtbetrag: 'Importo totale',
      waehrung: 'Valuta',
      kilometerstand: 'Chilometraggio',
      beschreibung: 'Descrizione',
      kategorie: 'Categoria',
      betrag: 'Importo',
      positionEntfernen: 'Rimuovi voce',
      positionHinzufuegen: 'Aggiungi voce',
    },
    wartung: {
      bearbeiten: 'Modifica manutenzione',
      typ: 'Tipo',
      beschreibung: 'Descrizione',
      erledigtAm: 'Fatto il',
      kilometerstand: 'Chilometraggio',
      naechsterTermin: 'Prossima scadenza',
      naechsterKm: 'Prossimo chilometraggio',
      status: 'Stato',
      erledigt: 'Fatto',
      faellig: 'In scadenza',
      ueberfaellig: 'Scaduto',
    },
    fahrzeugBearbeiten: 'Modifica veicolo',
    neueRechnung: 'Nuova fattura',
    neueWartung: 'Nuova manutenzione',
    loeschen: {
      rechnung: 'Eliminare la fattura?',
      wartung: 'Eliminare la manutenzione?',
      endgueltig: 'Questa azione non può essere annullata.',
      plan: 'Ripristinare il piano di manutenzione?',
      planText: 'Il piano di manutenzione specifico del veicolo viene eliminato e si usano gli intervalli standard.',
      fahrzeug: 'Eliminare il veicolo?',
      fahrzeugText: 'Vengono eliminate anche tutte le fatture e le manutenzioni.',
      fahrzeugHinweis: 'Venduto? Allora meglio «Segna come venduto»: il veicolo sparisce dalle scadenze, costi e fatture restano per la chiusura annuale.',
    },
  },
  en: {
    verkauftEintragen: 'Mark as sold',
    verkauftHinweis: (vermerk: string) => `${vermerk}. Costs and invoices are kept.`,
    dochBehalten: 'Keep it after all',
    kmAendern: 'Change mileage',
    tabs: {
      plan: 'Schedule',
      verlauf: 'History',
      rechnungen: 'Invoices',
      kosten: 'Costs',
    },
    plan: {
      ausServiceheft: 'Intervals from the service book',
      intervalleBearbeiten: 'Edit intervals',
      zuruecksetzen: 'Reset',
      allgemein: 'Due dates based on general intervals. With the service book they match exactly this vehicle, and the stamps are recorded as maintenance straight away.',
      serviceheftFotografieren: 'Photograph the service book',
      monate: (n: number) => `${n} months`,
      zuletzt: 'Last:',
      beiKm: (km: string) => `at ${km} km`,
      eintragen: 'Record',
      eintragenTitel: (arbeit: string) => `Record: ${arbeit}`,
    },
    verlauf: {
      wartungHinzufuegen: 'Add maintenance',
      geplant: 'Planned',
      terminAm: (datum: string) => `Appointment on ${datum}`,
      eintragBearbeiten: 'Edit entry',
      eintragLoeschen: 'Delete entry',
      leer: 'No maintenance recorded yet. You enter when each job was last done in the maintenance schedule.',
    },
    rechnungen: {
      hinzufuegen: 'Add invoice',
      ohneWerkstatt: 'No garage',
      scanAusstehend: 'Scan pending',
      leer: 'No invoices. Use «Add invoice» to upload a photo or PDF of the garage invoice, the AI fills in the form.',
    },
    kosten: {
      csvTipp: 'All invoice lines as a table for Excel',
      csv: 'CSV for Excel',
      pdfTipp: 'Vehicle data, maintenance, costs and invoices, for you and your accountant',
      pdf: 'Cost report (PDF)',
      serviceheftTipp: 'Summary, maintenance history and invoices as a folder for the buyer',
      serviceheft: 'Service book for the sale',
      mitPreisen: 'with prices',
      tabelle: 'Costs per year',
      kategorie: 'Category',
      total: 'Total',
      umgerechnet: (n: number, waehrung: string) => `${n} ${n === 1 ? 'invoice' : 'invoices'} in a foreign currency, converted to ${waehrung} at the ECB rate on the invoice date.`,
      ohneKurs: (n: number) => `${n} ${n === 1 ? 'invoice' : 'invoices'} in a foreign currency without a rate, shown in a separate column.`,
      leer: 'No invoices recorded yet, so no costs. The PDF dossier still works, with vehicle data and maintenance.',
    },
    rechnung: {
      titel: 'Invoice',
      vergroessern: 'Click to enlarge',
      positionen: 'Lines',
      bearbeiten: 'Edit invoice',
      werkstatt: 'Garage',
      datum: 'Date',
      gesamtbetrag: 'Total amount',
      waehrung: 'Currency',
      kilometerstand: 'Mileage',
      beschreibung: 'Description',
      kategorie: 'Category',
      betrag: 'Amount',
      positionEntfernen: 'Remove line',
      positionHinzufuegen: 'Add line',
    },
    wartung: {
      bearbeiten: 'Edit maintenance entry',
      typ: 'Type',
      beschreibung: 'Description',
      erledigtAm: 'Done on',
      kilometerstand: 'Mileage',
      naechsterTermin: 'Next due date',
      naechsterKm: 'Next mileage',
      status: 'Status',
      erledigt: 'Done',
      faellig: 'Due',
      ueberfaellig: 'Overdue',
    },
    fahrzeugBearbeiten: 'Edit vehicle',
    neueRechnung: 'New invoice',
    neueWartung: 'New maintenance',
    loeschen: {
      rechnung: 'Delete invoice?',
      wartung: 'Delete maintenance entry?',
      endgueltig: 'This action cannot be undone.',
      plan: 'Reset maintenance schedule?',
      planText: 'The schedule for this vehicle is deleted and the standard intervals are used.',
      fahrzeug: 'Delete vehicle?',
      fahrzeugText: 'All invoices and maintenance entries are deleted as well.',
      fahrzeugHinweis: 'Sold? Then better use «Mark as sold»: the vehicle disappears from the due list, costs and invoices stay for the annual accounts.',
    },
  },
} satisfies Record<Sprache, typeof de>
