import type { Sprache } from '../../lib/sprache'

// Rückfragen an Testkonten im Namen von Goran (services/trial-feedback.ts, scripts/reminders.ts): Tag 21 der
// Testzeit und Tag 31 ohne Abo. Antwort per Reply. Texte von Goran freigegeben, Versand mit TRIAL_FEEDBACK_MAILS=on;
// Französisch siezt wie die App. Textänderungen nur nach Gorans Freigabe.
const de = {
  tag21: {
    betreff: 'Wartungsheft: drei Wochen Testzeit, wie läuft es?',
    text: [
      'Hallo',
      '',
      'Ich bin Goran. Ich baue Wartungsheft selbst und lese jede Antwort persönlich. Du nutzt die App jetzt seit drei Wochen, deshalb drei Fragen:',
      '',
      '1. Was hat dir gefallen?',
      '2. Was hat genervt oder gefehlt? Bitte schonungslos ehrlich, Kritik hilft mir am meisten.',
      '3. Würdest du Wartungsheft weiterempfehlen?',
      '',
      'Freiwillig, falls du magst:',
      '- Nutzt du die App privat oder geschäftlich?',
      '- Welchen Beruf hast du?',
      '- Wie alt bist du?',
      '- Wie vertraut bist du mit Apps und IT?',
      '',
      'Zwei Zeilen als Antwort genügen, einfach auf diese Mail antworten.',
      '',
      'Danke und Gruss',
      'Goran',
      '',
      'Goran Strainovic, Wartungsheft',
      '',
      'Keine solchen Mails mehr: https://wartungsheft.ch/settings, Abschnitt «Erinnerungen».',
    ].join('\n'),
  },
  tag31: {
    betreff: 'Wartungsheft: eine Frage nach der Testzeit',
    text: [
      'Hallo',
      '',
      'Deine Testzeit bei Wartungsheft ist vorbei, danke fürs Ausprobieren. Eine Frage hätte ich noch: Was hätte dich überzeugt? Also was hätte Wartungsheft können oder anders machen müssen, damit sich ein Abo für dich lohnt?',
      '',
      'Ein Satz als Antwort genügt, einfach auf diese Mail antworten. Deine Daten bleiben, Lesen, Erfassen von Hand und die Exporte gehen weiter.',
      '',
      'Gruss',
      'Goran',
      '',
      'Goran Strainovic, Wartungsheft',
      '',
      'Keine solchen Mails mehr: https://wartungsheft.ch/settings, Abschnitt «Erinnerungen».',
    ].join('\n'),
  },
}

export default {
  de,
  fr: {
    tag21: {
      betreff: 'Wartungsheft : trois semaines d’essai, comment ça se passe ?',
      text: [
        'Bonjour',
        '',
        'Je suis Goran. Je développe Wartungsheft moi-même et je lis chaque réponse personnellement. Vous utilisez l’application depuis trois semaines, d’où trois questions :',
        '',
        '1. Qu’est-ce qui vous a plu ?',
        '2. Qu’est-ce qui vous a agacé ou manqué ? Sans ménagement, s’il vous plaît : c’est la critique qui m’aide le plus.',
        '3. Recommanderiez-vous Wartungsheft ?',
        '',
        'Facultatif, si vous le souhaitez :',
        '- Utilisez-vous l’application à titre privé ou professionnel ?',
        '- Quel est votre métier ?',
        '- Quel âge avez-vous ?',
        '- À quel point êtes-vous à l’aise avec les applications et l’informatique ?',
        '',
        'Deux lignes suffisent, répondez simplement à cet e-mail.',
        '',
        'Merci et salutations',
        'Goran',
        '',
        'Goran Strainovic, Wartungsheft',
        '',
        'Plus d’e-mails de ce type : https://wartungsheft.ch/settings, rubrique « Rappels ».',
      ].join('\n'),
    },
    tag31: {
      betreff: 'Wartungsheft : une question après la période d’essai',
      text: [
        'Bonjour',
        '',
        'Votre période d’essai de Wartungsheft est terminée, merci d’avoir essayé. J’aurais encore une question : qu’aurait-il fallu pour vous convaincre ? Autrement dit, qu’est-ce que Wartungsheft aurait dû savoir faire ou faire autrement pour qu’un abonnement en vaille la peine pour vous ?',
        '',
        'Une phrase suffit, répondez simplement à cet e-mail. Vos données restent, la consultation, la saisie manuelle et les exports continuent de fonctionner.',
        '',
        'Salutations',
        'Goran',
        '',
        'Goran Strainovic, Wartungsheft',
        '',
        'Plus d’e-mails de ce type : https://wartungsheft.ch/settings, rubrique « Rappels ».',
      ].join('\n'),
    },
  },
  it: {
    tag21: {
      betreff: 'Wartungsheft: tre settimane di prova, come va?',
      text: [
        'Ciao',
        '',
        'Sono Goran. Sviluppo Wartungsheft da solo e leggo personalmente ogni risposta. Usi l\'app da tre settimane, quindi tre domande:',
        '',
        '1. Che cosa ti è piaciuto?',
        '2. Che cosa ti ha dato fastidio o ti è mancato? Senza riguardi, per favore: le critiche sono ciò che mi aiuta di più.',
        '3. Consiglieresti Wartungsheft ad altri?',
        '',
        'Facoltativo, se vuoi:',
        '- Usi l\'app per scopi privati o aziendali?',
        '- Che lavoro fai?',
        '- Quanti anni hai?',
        '- Quanta dimestichezza hai con app e informatica?',
        '',
        'Bastano due righe, rispondi semplicemente a questa e-mail.',
        '',
        'Grazie e un saluto',
        'Goran',
        '',
        'Goran Strainovic, Wartungsheft',
        '',
        'Niente più e-mail di questo tipo: https://wartungsheft.ch/settings, sezione «Promemoria».',
      ].join('\n'),
    },
    tag31: {
      betreff: 'Wartungsheft: una domanda dopo il periodo di prova',
      text: [
        'Ciao',
        '',
        'Il tuo periodo di prova di Wartungsheft è terminato, grazie per averlo provato. Avrei ancora una domanda: che cosa ci sarebbe voluto per convincerti? Cioè, che cosa avrebbe dovuto saper fare o fare diversamente Wartungsheft perché un abbonamento valesse la pena per te?',
        '',
        'Basta una frase, rispondi semplicemente a questa e-mail. I tuoi dati restano, lettura, registrazione manuale ed esportazioni continuano a funzionare.',
        '',
        'Un saluto',
        'Goran',
        '',
        'Goran Strainovic, Wartungsheft',
        '',
        'Niente più e-mail di questo tipo: https://wartungsheft.ch/settings, sezione «Promemoria».',
      ].join('\n'),
    },
  },
  en: {
    tag21: {
      betreff: 'Wartungsheft: three weeks into your trial, how is it going?',
      text: [
        'Hello',
        '',
        'I am Goran. I build Wartungsheft myself and read every reply personally. You have been using the app for three weeks now, so three questions:',
        '',
        '1. What did you like?',
        '2. What annoyed you or was missing? Please be brutally honest, criticism helps me most.',
        '3. Would you recommend Wartungsheft to others?',
        '',
        'Optional, if you like:',
        '- Do you use the app privately or for a business?',
        '- What is your occupation?',
        '- How old are you?',
        '- How comfortable are you with apps and IT?',
        '',
        'Two lines are enough, just reply to this email.',
        '',
        'Thanks and best regards',
        'Goran',
        '',
        'Goran Strainovic, Wartungsheft',
        '',
        'No more emails like this: https://wartungsheft.ch/settings, section “Reminders”.',
      ].join('\n'),
    },
    tag31: {
      betreff: 'Wartungsheft: one question after your trial',
      text: [
        'Hello',
        '',
        'Your Wartungsheft trial has ended, thank you for trying it. One question remains: what would have convinced you? In other words, what would Wartungsheft have needed to do, or do differently, for a subscription to be worth it for you?',
        '',
        'One sentence is enough, just reply to this email. Your data stays, and reading, manual entry and exports keep working.',
        '',
        'Best regards',
        'Goran',
        '',
        'Goran Strainovic, Wartungsheft',
        '',
        'No more emails like this: https://wartungsheft.ch/settings, section “Reminders”.',
      ].join('\n'),
    },
  },
} satisfies Record<Sprache, typeof de>
