import type { Sprache } from '../../lib/sprache'

// Wartungskategorien (services/categories.ts) und die Standard-Bezeichnungen des Wartungsplans.
// Einzige Label-Tabelle: categoryLabel in services/report.ts, planLabel in services/maintenance-schedule.ts.
const de = {
  kategorien: {
    oelwechsel: 'Ölwechsel',
    inspektion: 'Inspektion / Service',
    bremsen: 'Bremsen',
    reifen: 'Reifen',
    luftfilter: 'Luftfilter',
    zahnriemen: 'Zahnriemen',
    bremsflüssigkeit: 'Bremsflüssigkeit',
    klimaanlage: 'Klimaanlage',
    tuev: 'MFK / Prüfung',
    karosserie: 'Karosserie',
    elektrik: 'Elektrik',
    fahrwerk: 'Fahrwerk',
    auspuff: 'Auspuff',
    kuehlung: 'Kühlung',
    autoglas: 'Autoglas',
    sonstiges: 'Sonstiges',
    nicht_zugeordnet: 'Nicht zugeordnet / MwSt.',
  },
  /** Bezeichnungen des Standard-Wartungsplans, Schlüssel ist die Art */
  plan: {
    oelwechsel: 'Ölwechsel',
    inspektion: 'Inspektion',
    bremsen: 'Bremsen prüfen',
    reifen: 'Reifenwechsel',
    luftfilter: 'Luftfilter',
    zahnriemen: 'Zahnriemen',
    bremsflüssigkeit: 'Bremsflüssigkeit',
    klimaanlage: 'Klimaanlage Service',
    tuev: 'MFK / Prüfung',
  },
}

export default {
  de,
  fr: {
    kategorien: {
      oelwechsel: 'Vidange',
      inspektion: 'Inspection / service',
      bremsen: 'Freins',
      reifen: 'Pneus',
      luftfilter: 'Filtre à air',
      zahnriemen: 'Courroie de distribution',
      bremsflüssigkeit: 'Liquide de frein',
      klimaanlage: 'Climatisation',
      tuev: 'Expertise (MFK)',
      karosserie: 'Carrosserie',
      elektrik: 'Électricité',
      fahrwerk: 'Train roulant',
      auspuff: 'Échappement',
      kuehlung: 'Refroidissement',
      autoglas: 'Vitrage',
      sonstiges: 'Divers',
      nicht_zugeordnet: 'Non attribué / TVA',
    },
    plan: {
      oelwechsel: 'Vidange',
      inspektion: 'Service',
      bremsen: 'Contrôle des freins',
      reifen: 'Changement de pneus',
      luftfilter: 'Filtre à air',
      zahnriemen: 'Courroie de distribution',
      bremsflüssigkeit: 'Liquide de frein',
      klimaanlage: 'Service de climatisation',
      tuev: 'Expertise (MFK)',
    },
  },
  it: {
    kategorien: {
      oelwechsel: 'Cambio dell\'olio',
      inspektion: 'Ispezione / servizio',
      bremsen: 'Freni',
      reifen: 'Pneumatici',
      luftfilter: 'Filtro dell\'aria',
      zahnriemen: 'Cinghia di distribuzione',
      bremsflüssigkeit: 'Liquido dei freni',
      klimaanlage: 'Climatizzatore',
      tuev: 'Collaudo (MFK)',
      karosserie: 'Carrozzeria',
      elektrik: 'Impianto elettrico',
      fahrwerk: 'Telaio e sospensioni',
      auspuff: 'Scarico',
      kuehlung: 'Raffreddamento',
      autoglas: 'Cristalli',
      sonstiges: 'Altro',
      nicht_zugeordnet: 'Non assegnato / IVA',
    },
    plan: {
      oelwechsel: 'Cambio dell\'olio',
      inspektion: 'Servizio',
      bremsen: 'Controllo dei freni',
      reifen: 'Cambio pneumatici',
      luftfilter: 'Filtro dell\'aria',
      zahnriemen: 'Cinghia di distribuzione',
      bremsflüssigkeit: 'Liquido dei freni',
      klimaanlage: 'Servizio climatizzatore',
      tuev: 'Collaudo (MFK)',
    },
  },
  en: {
    kategorien: {
      oelwechsel: 'Oil change',
      inspektion: 'Inspection / service',
      bremsen: 'Brakes',
      reifen: 'Tyres',
      luftfilter: 'Air filter',
      zahnriemen: 'Timing belt',
      bremsflüssigkeit: 'Brake fluid',
      klimaanlage: 'Air conditioning',
      tuev: 'Vehicle inspection (MFK)',
      karosserie: 'Bodywork',
      elektrik: 'Electrics',
      fahrwerk: 'Suspension and steering',
      auspuff: 'Exhaust',
      kuehlung: 'Cooling',
      autoglas: 'Glass',
      sonstiges: 'Other',
      nicht_zugeordnet: 'Unassigned / VAT',
    },
    plan: {
      oelwechsel: 'Oil change',
      inspektion: 'Service',
      bremsen: 'Brake check',
      reifen: 'Tyre change',
      luftfilter: 'Air filter',
      zahnriemen: 'Timing belt',
      bremsflüssigkeit: 'Brake fluid',
      klimaanlage: 'Air conditioning service',
      tuev: 'Vehicle inspection (MFK)',
    },
  },
} satisfies Record<Sprache, typeof de>
