import type { Sprache } from '../../lib/sprache'

// Eingebaute Texte der PrimeVue-Komponenten (Dialog schliessen, leere Auswahl, Kalender), gesetzt in
// src/lib/primevue-sprache.ts. Nur die Schlüssel, die die App braucht; der Rest bleibt PrimeVue-Standard.
const de = {
  accept: 'Ja',
  reject: 'Nein',
  choose: 'Auswählen',
  upload: 'Hochladen',
  cancel: 'Abbrechen',
  clear: 'Leeren',
  apply: 'Übernehmen',
  today: 'Heute',
  dateFormat: 'dd.mm.yy',
  emptyMessage: 'Keine Optionen vorhanden',
  emptyFilterMessage: 'Keine Treffer',
  emptySearchMessage: 'Keine Treffer',
  noFileChosenMessage: 'Keine Datei ausgewählt',
  dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
  dayNamesShort: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  dayNamesMin: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  monthNames: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
  monthNamesShort: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
  aria: {
    close: 'Schliessen',
    previous: 'Zurück',
    next: 'Weiter',
    navigation: 'Navigation',
    trueLabel: 'Ja',
    falseLabel: 'Nein',
    nullLabel: 'Nicht ausgewählt',
    listLabel: 'Auswahlliste',
    zoomImage: 'Bild vergrössern',
    zoomIn: 'Vergrössern',
    zoomOut: 'Verkleinern',
    rotateRight: 'Nach rechts drehen',
    rotateLeft: 'Nach links drehen',
  },
}

export default {
  de,
  fr: {
    accept: 'Oui',
    reject: 'Non',
    choose: 'Choisir',
    upload: 'Téléverser',
    cancel: 'Annuler',
    clear: 'Effacer',
    apply: 'Appliquer',
    today: 'Aujourd’hui',
    dateFormat: 'dd.mm.yy',
    emptyMessage: 'Aucune option disponible',
    emptyFilterMessage: 'Aucun résultat',
    emptySearchMessage: 'Aucun résultat',
    noFileChosenMessage: 'Aucun fichier choisi',
    dayNames: ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
    dayNamesShort: ['dim.', 'lun.', 'mar.', 'mer.', 'jeu.', 'ven.', 'sam.'],
    dayNamesMin: ['di', 'lu', 'ma', 'me', 'je', 've', 'sa'],
    monthNames: ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
    monthNamesShort: ['janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin', 'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.'],
    aria: {
      close: 'Fermer',
      previous: 'Précédent',
      next: 'Suivant',
      navigation: 'Navigation',
      trueLabel: 'Oui',
      falseLabel: 'Non',
      nullLabel: 'Non sélectionné',
      listLabel: 'Liste d’options',
      zoomImage: 'Agrandir l’image',
      zoomIn: 'Agrandir',
      zoomOut: 'Réduire',
      rotateRight: 'Tourner à droite',
      rotateLeft: 'Tourner à gauche',
    },
  },
  it: {
    accept: 'Sì',
    reject: 'No',
    choose: 'Scegli',
    upload: 'Carica',
    cancel: 'Annulla',
    clear: 'Svuota',
    apply: 'Applica',
    today: 'Oggi',
    dateFormat: 'dd.mm.yy',
    emptyMessage: 'Nessuna opzione disponibile',
    emptyFilterMessage: 'Nessun risultato',
    emptySearchMessage: 'Nessun risultato',
    noFileChosenMessage: 'Nessun file scelto',
    dayNames: ['domenica', 'lunedì', 'martedì', 'mercoledì', 'giovedì', 'venerdì', 'sabato'],
    dayNamesShort: ['dom', 'lun', 'mar', 'mer', 'gio', 'ven', 'sab'],
    dayNamesMin: ['do', 'lu', 'ma', 'me', 'gi', 've', 'sa'],
    monthNames: ['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'],
    monthNamesShort: ['gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic'],
    aria: {
      close: 'Chiudi',
      previous: 'Precedente',
      next: 'Successivo',
      navigation: 'Navigazione',
      trueLabel: 'Sì',
      falseLabel: 'No',
      nullLabel: 'Non selezionato',
      listLabel: 'Elenco di opzioni',
      zoomImage: 'Ingrandisci immagine',
      zoomIn: 'Ingrandisci',
      zoomOut: 'Riduci',
      rotateRight: 'Ruota a destra',
      rotateLeft: 'Ruota a sinistra',
    },
  },
  en: {
    accept: 'Yes',
    reject: 'No',
    choose: 'Choose',
    upload: 'Upload',
    cancel: 'Cancel',
    clear: 'Clear',
    apply: 'Apply',
    today: 'Today',
    dateFormat: 'dd/mm/yy',
    emptyMessage: 'No available options',
    emptyFilterMessage: 'No results found',
    emptySearchMessage: 'No results found',
    noFileChosenMessage: 'No file chosen',
    dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    aria: {
      close: 'Close',
      previous: 'Previous',
      next: 'Next',
      navigation: 'Navigation',
      trueLabel: 'Yes',
      falseLabel: 'No',
      nullLabel: 'Not selected',
      listLabel: 'Option list',
      zoomImage: 'Zoom image',
      zoomIn: 'Zoom in',
      zoomOut: 'Zoom out',
      rotateRight: 'Rotate right',
      rotateLeft: 'Rotate left',
    },
  },
} satisfies Record<Sprache, typeof de>
