import type { Sprache } from '../../lib/sprache'

// Formular «Neue Rechnung» (InvoiceForm.vue, InvoiceFormDialog.vue), Rechnungs-Scan (useInvoiceScan.ts) und
// Prüfliste mehrerer Rechnungen (services/invoice-scan.ts)
const de = {
  neueRechnung: 'Neue Rechnung',
  andereWaehlen: 'Andere Rechnung wählen',
  fotografieren: 'Rechnung fotografieren oder PDF wählen',
  ansagen: 'Rechnung ansagen',
  ansageBeispiel: 'Oder ansagen: «Muster-Garage, 14. September, 486.50, 118\'400 Kilometer, Ölwechsel und Bremsbeläge vorne.»',
  ansageLaeuft: 'Ansage wird ausgewertet …',
  ansage: 'Ansage',
  mehrere: 'Mehrere Fotos oder ein PDF mit mehreren Rechnungen werden einzeln erfasst.',
  bildAlt: 'Rechnung',
  pdfNurGelesen: 'PDF wird nur gelesen, nicht als Bild gespeichert.',
  erkannteRechnungen: 'Erkannte Rechnungen',
  werkstattUnbekannt: 'Werkstatt unbekannt',
  positionen: (n: number) => n === 1 ? `${n} Position` : `${n} Positionen`,
  duplikat: {
    'bereits erfasst': 'bereits erfasst',
    'doppelt im Beleg': 'doppelt im Beleg',
  },
  positionenZuViel: 'Positionen ergeben mehr als das Total',
  nichtLesbar: 'Nicht lesbar',
  datumOderBetragFehlt: 'Datum oder Betrag fehlt',
  fahrzeugFuer: (n: number) => `Fahrzeug für Rechnung ${n}`,
  datum: 'Datum *',
  werkstatt: 'Werkstatt',
  betrag: 'Betrag',
  kilometerstand: 'Kilometerstand',
  erkanntePositionen: 'Erkannte Positionen',
  positionEntfernen: 'Position entfernen',
  positionenWarnung: (summe: string, total: string) => `Positionen ergeben ${summe}, die Rechnung ${total}. Bitte Positionen prüfen.`,
  kategorie: 'Kategorie',
  beschreibung: 'Beschreibung',
  speichernN: (n: number) => n === 1 ? '1 Rechnung speichern' : `${n} Rechnungen speichern`,
  validierung: {
    datumPflicht: 'Datum ist erforderlich',
    betragPositiv: 'Betrag muss positiv sein',
    kmPositiv: 'Kilometerstand muss positiv sein',
  },
  scan: {
    nurFotoPdf: (name: string) => `${name}: nur Fotos oder PDF möglich.`,
    zuGross: (name: string, mb: number) => `${name}: Datei zu gross (max. ${mb} MB).`,
    offline: 'Offline: Die Rechnung wird gespeichert, der Scan läuft nach, sobald du wieder online bist.',
    ausrichten: 'Rechnung wird ausgerichtet und gelesen …',
    zaehler: (i: number, n: number) => ` (${i} von ${n})`,
    pdfLesen: (zaehler: string) => `PDF wird gelesen${zaehler} …`,
    pdfSeite: (fertig: number, total: number, zaehler: string) => `PDF: Seite ${fertig} von ${total} ausgewertet${zaehler} …`,
    fotoLesen: (zaehler: string) => `Foto wird gelesen${zaehler} …`,
    nichtLesbarListe: (liste: string) => ` Nicht lesbar: ${liste}.`,
    keineRechnung: 'Auf den Fotos war keine Rechnung zu lesen. Bitte Felder selbst ausfüllen.',
    erkannt: (n: number) => `${n} Rechnungen erkannt`,
    davonDoppelt: (n: number) => `, davon ${n} schon erfasst oder doppelt`,
    anderesSchild: (n: number) => `, ${n} mit anderem Kontrollschild`,
    bittePruefen: 'Bitte prüfen.',
    selbstAusfuellen: (meldung: string) => `${meldung} Felder bitte selbst ausfüllen.`,
    ausgefuellt: 'Felder aus der Rechnung ausgefüllt. Bitte prüfen.',
    nichtsVerwertbar: 'Auf dem Foto war nichts Verwertbares zu lesen. Bitte Felder selbst ausfüllen.',
    achtung: (hinweis: string) => ` Achtung: ${hinweis}.`,
    achtungAnderes: (hinweis: string) => ` Achtung: Rechnung nennt ${hinweis}, nicht dieses Fahrzeug.`,
  },
  stapel: {
    seite: (n: number) => `Seite ${n}`,
    seitenBereich: (von: number, bis: number) => `Seite ${von}–${bis}`,
    seiten: (liste: string) => `Seiten ${liste}`,
    schildUnbekannt: (schild: string) => `Kontrollschild ${schild} gehört zu keinem Fahrzeug`,
    schildFahrzeug: (schild: string, fahrzeug: string) => `Kontrollschild ${schild}: ${fahrzeug}`,
  },
}

export default {
  de,
  fr: {
    neueRechnung: 'Nouvelle facture',
    andereWaehlen: 'Choisir une autre facture',
    fotografieren: 'Photographier la facture ou choisir un PDF',
    ansagen: 'Dicter la facture',
    ansageBeispiel: 'Ou dicte : « Garage Exemple, 14 septembre, 486.50, 118\'400 kilomètres, vidange et plaquettes de frein avant. »',
    ansageLaeuft: 'Analyse de la dictée …',
    ansage: 'Dictée',
    mehrere: 'Plusieurs photos ou un PDF avec plusieurs factures sont saisis séparément.',
    bildAlt: 'Facture',
    pdfNurGelesen: 'Le PDF est seulement lu, pas enregistré comme image.',
    erkannteRechnungen: 'Factures reconnues',
    werkstattUnbekannt: 'Garage inconnu',
    positionen: (n: number) => n === 1 ? `${n} poste` : `${n} postes`,
    duplikat: {
      'bereits erfasst': 'déjà saisie',
      'doppelt im Beleg': 'en double dans le document',
    },
    positionenZuViel: 'Les postes dépassent le total',
    nichtLesbar: 'Illisible',
    datumOderBetragFehlt: 'Date ou montant manquant',
    fahrzeugFuer: (n: number) => `Véhicule pour la facture ${n}`,
    datum: 'Date *',
    werkstatt: 'Garage',
    betrag: 'Montant',
    kilometerstand: 'Kilométrage',
    erkanntePositionen: 'Postes reconnus',
    positionEntfernen: 'Retirer le poste',
    positionenWarnung: (summe: string, total: string) => `Les postes totalisent ${summe}, la facture ${total}. Vérifie les postes.`,
    kategorie: 'Catégorie',
    beschreibung: 'Description',
    speichernN: (n: number) => n === 1 ? 'Enregistrer 1 facture' : `Enregistrer ${n} factures`,
    validierung: {
      datumPflicht: 'La date est obligatoire',
      betragPositiv: 'Le montant doit être positif',
      kmPositiv: 'Le kilométrage doit être positif',
    },
    scan: {
      nurFotoPdf: (name: string) => `${name} : seulement des photos ou un PDF.`,
      zuGross: (name: string, mb: number) => `${name} : fichier trop volumineux (max. ${mb} Mo).`,
      offline: 'Hors ligne : la facture est enregistrée, l\'analyse suivra dès que tu seras de nouveau en ligne.',
      ausrichten: 'Redressement et lecture de la facture …',
      zaehler: (i: number, n: number) => ` (${i} sur ${n})`,
      pdfLesen: (zaehler: string) => `Lecture du PDF${zaehler} …`,
      pdfSeite: (fertig: number, total: number, zaehler: string) => `PDF : page ${fertig} sur ${total} analysée${zaehler} …`,
      fotoLesen: (zaehler: string) => `Lecture de la photo${zaehler} …`,
      nichtLesbarListe: (liste: string) => ` Illisible : ${liste}.`,
      keineRechnung: 'Aucune facture lisible sur les photos. Remplis les champs toi-même.',
      erkannt: (n: number) => `${n} factures reconnues`,
      davonDoppelt: (n: number) => `, dont ${n} déjà saisies ou en double`,
      anderesSchild: (n: number) => `, ${n} avec une autre plaque`,
      bittePruefen: 'Vérifie-les.',
      selbstAusfuellen: (meldung: string) => `${meldung} Remplis les champs toi-même.`,
      ausgefuellt: 'Champs remplis à partir de la facture. Vérifie-les.',
      nichtsVerwertbar: 'Rien d\'exploitable sur la photo. Remplis les champs toi-même.',
      achtung: (hinweis: string) => ` Attention : ${hinweis}.`,
      achtungAnderes: (hinweis: string) => ` Attention : la facture mentionne ${hinweis}, pas ce véhicule.`,
    },
    stapel: {
      seite: (n: number) => `Page ${n}`,
      seitenBereich: (von: number, bis: number) => `Pages ${von}–${bis}`,
      seiten: (liste: string) => `Pages ${liste}`,
      schildUnbekannt: (schild: string) => `la plaque ${schild} n'appartient à aucun véhicule`,
      schildFahrzeug: (schild: string, fahrzeug: string) => `plaque ${schild} : ${fahrzeug}`,
    },
  },
  it: {
    neueRechnung: 'Nuova fattura',
    andereWaehlen: 'Scegli un\'altra fattura',
    fotografieren: 'Fotografa la fattura o scegli un PDF',
    ansagen: 'Detta la fattura',
    ansageBeispiel: 'Oppure detta: «Garage Esempio, 14 settembre, 486.50, 118\'400 chilometri, cambio dell\'olio e pastiglie dei freni anteriori.»',
    ansageLaeuft: 'Analisi del dettato …',
    ansage: 'Dettato',
    mehrere: 'Più foto o un PDF con più fatture vengono registrati singolarmente.',
    bildAlt: 'Fattura',
    pdfNurGelesen: 'Il PDF viene solo letto, non salvato come immagine.',
    erkannteRechnungen: 'Fatture riconosciute',
    werkstattUnbekannt: 'Officina sconosciuta',
    positionen: (n: number) => n === 1 ? `${n} voce` : `${n} voci`,
    duplikat: {
      'bereits erfasst': 'già registrata',
      'doppelt im Beleg': 'doppia nel documento',
    },
    positionenZuViel: 'Le voci superano il totale',
    nichtLesbar: 'Illeggibile',
    datumOderBetragFehlt: 'Manca la data o l\'importo',
    fahrzeugFuer: (n: number) => `Veicolo per la fattura ${n}`,
    datum: 'Data *',
    werkstatt: 'Officina',
    betrag: 'Importo',
    kilometerstand: 'Chilometraggio',
    erkanntePositionen: 'Voci riconosciute',
    positionEntfernen: 'Rimuovi voce',
    positionenWarnung: (summe: string, total: string) => `Le voci sommano ${summe}, la fattura ${total}. Controlla le voci.`,
    kategorie: 'Categoria',
    beschreibung: 'Descrizione',
    speichernN: (n: number) => n === 1 ? 'Salva 1 fattura' : `Salva ${n} fatture`,
    validierung: {
      datumPflicht: 'La data è obbligatoria',
      betragPositiv: 'L\'importo deve essere positivo',
      kmPositiv: 'Il chilometraggio deve essere positivo',
    },
    scan: {
      nurFotoPdf: (name: string) => `${name}: solo foto o PDF.`,
      zuGross: (name: string, mb: number) => `${name}: file troppo grande (max. ${mb} MB).`,
      offline: 'Offline: la fattura viene salvata, la scansione seguirà appena sarai di nuovo online.',
      ausrichten: 'Raddrizzamento e lettura della fattura …',
      zaehler: (i: number, n: number) => ` (${i} di ${n})`,
      pdfLesen: (zaehler: string) => `Lettura del PDF${zaehler} …`,
      pdfSeite: (fertig: number, total: number, zaehler: string) => `PDF: pagina ${fertig} di ${total} analizzata${zaehler} …`,
      fotoLesen: (zaehler: string) => `Lettura della foto${zaehler} …`,
      nichtLesbarListe: (liste: string) => ` Illeggibile: ${liste}.`,
      keineRechnung: 'Nessuna fattura leggibile nelle foto. Compila tu i campi.',
      erkannt: (n: number) => `${n} fatture riconosciute`,
      davonDoppelt: (n: number) => `, di cui ${n} già registrate o doppie`,
      anderesSchild: (n: number) => `, ${n} con un'altra targa`,
      bittePruefen: 'Controllale.',
      selbstAusfuellen: (meldung: string) => `${meldung} Compila tu i campi.`,
      ausgefuellt: 'Campi compilati dalla fattura. Controllali.',
      nichtsVerwertbar: 'Nella foto non c\'era nulla di utilizzabile. Compila tu i campi.',
      achtung: (hinweis: string) => ` Attenzione: ${hinweis}.`,
      achtungAnderes: (hinweis: string) => ` Attenzione: la fattura indica ${hinweis}, non questo veicolo.`,
    },
    stapel: {
      seite: (n: number) => `Pagina ${n}`,
      seitenBereich: (von: number, bis: number) => `Pagine ${von}–${bis}`,
      seiten: (liste: string) => `Pagine ${liste}`,
      schildUnbekannt: (schild: string) => `la targa ${schild} non appartiene a nessun veicolo`,
      schildFahrzeug: (schild: string, fahrzeug: string) => `targa ${schild}: ${fahrzeug}`,
    },
  },
  en: {
    neueRechnung: 'New invoice',
    andereWaehlen: 'Choose another invoice',
    fotografieren: 'Photograph the invoice or choose a PDF',
    ansagen: 'Dictate the invoice',
    ansageBeispiel: 'Or dictate: “Sample Garage, 14 September, 486.50, 118,400 kilometres, oil change and front brake pads.”',
    ansageLaeuft: 'Processing the dictation …',
    ansage: 'Dictation',
    mehrere: 'Several photos or a PDF with several invoices are recorded one by one.',
    bildAlt: 'Invoice',
    pdfNurGelesen: 'The PDF is only read, not saved as an image.',
    erkannteRechnungen: 'Recognised invoices',
    werkstattUnbekannt: 'Garage unknown',
    positionen: (n: number) => n === 1 ? `${n} line item` : `${n} line items`,
    duplikat: {
      'bereits erfasst': 'already recorded',
      'doppelt im Beleg': 'duplicate in the document',
    },
    positionenZuViel: 'Line items add up to more than the total',
    nichtLesbar: 'Not readable',
    datumOderBetragFehlt: 'Date or amount missing',
    fahrzeugFuer: (n: number) => `Vehicle for invoice ${n}`,
    datum: 'Date *',
    werkstatt: 'Garage',
    betrag: 'Amount',
    kilometerstand: 'Mileage',
    erkanntePositionen: 'Recognised line items',
    positionEntfernen: 'Remove line item',
    positionenWarnung: (summe: string, total: string) => `The line items add up to ${summe}, the invoice to ${total}. Please check the line items.`,
    kategorie: 'Category',
    beschreibung: 'Description',
    speichernN: (n: number) => n === 1 ? 'Save 1 invoice' : `Save ${n} invoices`,
    validierung: {
      datumPflicht: 'Date is required',
      betragPositiv: 'Amount must be positive',
      kmPositiv: 'Mileage must be positive',
    },
    scan: {
      nurFotoPdf: (name: string) => `${name}: only photos or PDF.`,
      zuGross: (name: string, mb: number) => `${name}: file too large (max. ${mb} MB).`,
      offline: 'Offline: the invoice is saved and will be scanned as soon as you are back online.',
      ausrichten: 'Straightening and reading the invoice …',
      zaehler: (i: number, n: number) => ` (${i} of ${n})`,
      pdfLesen: (zaehler: string) => `Reading PDF${zaehler} …`,
      pdfSeite: (fertig: number, total: number, zaehler: string) => `PDF: page ${fertig} of ${total} processed${zaehler} …`,
      fotoLesen: (zaehler: string) => `Reading photo${zaehler} …`,
      nichtLesbarListe: (liste: string) => ` Not readable: ${liste}.`,
      keineRechnung: 'No invoice could be read from the photos. Please fill in the fields yourself.',
      erkannt: (n: number) => `${n} invoices recognised`,
      davonDoppelt: (n: number) => `, ${n} of them already recorded or duplicates`,
      anderesSchild: (n: number) => `, ${n} with a different number plate`,
      bittePruefen: 'Please check.',
      selbstAusfuellen: (meldung: string) => `${meldung} Please fill in the fields yourself.`,
      ausgefuellt: 'Fields filled in from the invoice. Please check.',
      nichtsVerwertbar: 'Nothing usable could be read from the photo. Please fill in the fields yourself.',
      achtung: (hinweis: string) => ` Note: ${hinweis}.`,
      achtungAnderes: (hinweis: string) => ` Note: the invoice mentions ${hinweis}, not this vehicle.`,
    },
    stapel: {
      seite: (n: number) => `Page ${n}`,
      seitenBereich: (von: number, bis: number) => `Pages ${von}–${bis}`,
      seiten: (liste: string) => `Pages ${liste}`,
      schildUnbekannt: (schild: string) => `number plate ${schild} does not belong to any vehicle`,
      schildFahrzeug: (schild: string, fahrzeug: string) => `number plate ${schild}: ${fahrzeug}`,
    },
  },
} satisfies Record<Sprache, typeof de>
