import type { Sprache } from '../../lib/sprache'

// Rückmeldung an den Betreiber (components/FeedbackDialog.vue) und Diktieren (components/DictateButton.vue,
// composables/useDictation.ts)
const de = {
  titel: 'Fehler melden oder Wunsch',
  intro: 'Was stört, was fehlt? Sprich es auf oder schreib es — beides landet direkt bei uns.',
  neuAufnehmen: 'Neu aufnehmen',
  aufnehmen: 'Sprachnachricht aufnehmen',
  stoppenDauer: (dauer: string) => `Aufnahme stoppen (${dauer})`,
  verwerfen: 'Verwerfen',
  keinMikrofon: 'Kein Zugriff aufs Mikrofon. Schreib die Rückmeldung einfach ins Feld unten.',
  platzhalter: 'Oder schreib es hier hin.',
  selbstSchreiben: 'Lieber selbst schreiben?',
  kopiert: 'Adresse kopiert',
  vonHand: 'Bitte von Hand kopieren.',
  danke: 'Danke, ist angekommen',
  dankeDetail: 'Wir melden uns, wenn es etwas zu sagen gibt.',
  senden: 'Senden',
  diktat: {
    diktieren: 'Diktieren',
    stoppen: 'Aufnahme stoppen',
    stoppenSekunden: (sekunden: number) => `Aufnahme stoppen (${sekunden} Sekunden)`,
    keinMikrofon: 'Kein Zugriff aufs Mikrofon. Bitte tippen.',
  },
}

export default {
  de,
  fr: {
    titel: 'Signaler un problème ou un souhait',
    intro: 'Qu’est-ce qui dérange, qu’est-ce qui manque ? Dis-le ou écris-le, les deux nous arrivent directement.',
    neuAufnehmen: 'Réenregistrer',
    aufnehmen: 'Enregistrer un message vocal',
    stoppenDauer: (dauer: string) => `Arrêter l’enregistrement (${dauer})`,
    verwerfen: 'Supprimer',
    keinMikrofon: 'Pas d’accès au micro. Écris simplement ton message dans le champ ci-dessous.',
    platzhalter: 'Ou écris-le ici.',
    selbstSchreiben: 'Tu préfères écrire toi-même ?',
    kopiert: 'Adresse copiée',
    vonHand: 'Copie-la à la main.',
    danke: 'Merci, c’est arrivé',
    dankeDetail: 'Nous te répondrons s’il y a quelque chose à dire.',
    senden: 'Envoyer',
    diktat: {
      diktieren: 'Dicter',
      stoppen: 'Arrêter l’enregistrement',
      stoppenSekunden: (sekunden: number) => `Arrêter l’enregistrement (${sekunden} secondes)`,
      keinMikrofon: 'Pas d’accès au micro. Tape le texte.',
    },
  },
  it: {
    titel: 'Segnala un errore o un desiderio',
    intro: 'Cosa ti disturba, cosa manca? Dillo a voce o scrivilo: arriva direttamente a noi.',
    neuAufnehmen: 'Registra di nuovo',
    aufnehmen: 'Registra un messaggio vocale',
    stoppenDauer: (dauer: string) => `Ferma la registrazione (${dauer})`,
    verwerfen: 'Scarta',
    keinMikrofon: 'Nessun accesso al microfono. Scrivi semplicemente il messaggio nel campo qui sotto.',
    platzhalter: 'Oppure scrivilo qui.',
    selbstSchreiben: 'Preferisci scrivere tu?',
    kopiert: 'Indirizzo copiato',
    vonHand: 'Copialo a mano.',
    danke: 'Grazie, è arrivato',
    dankeDetail: 'Ci facciamo vivi se c\'è qualcosa da dire.',
    senden: 'Invia',
    diktat: {
      diktieren: 'Detta',
      stoppen: 'Ferma la registrazione',
      stoppenSekunden: (sekunden: number) => `Ferma la registrazione (${sekunden} secondi)`,
      keinMikrofon: 'Nessun accesso al microfono. Scrivi a mano.',
    },
  },
  en: {
    titel: 'Report a problem or a wish',
    intro: 'What bothers you, what is missing? Say it or write it, both reach us directly.',
    neuAufnehmen: 'Record again',
    aufnehmen: 'Record a voice message',
    stoppenDauer: (dauer: string) => `Stop recording (${dauer})`,
    verwerfen: 'Discard',
    keinMikrofon: 'No access to the microphone. Just type your message in the field below.',
    platzhalter: 'Or write it here.',
    selbstSchreiben: 'Prefer to write yourself?',
    kopiert: 'Address copied',
    vonHand: 'Please copy it by hand.',
    danke: 'Thanks, it has arrived',
    dankeDetail: 'We will get back to you if there is something to say.',
    senden: 'Send',
    diktat: {
      diktieren: 'Dictate',
      stoppen: 'Stop recording',
      stoppenSekunden: (sekunden: number) => `Stop recording (${sekunden} seconds)`,
      keinMikrofon: 'No access to the microphone. Please type.',
    },
  },
} satisfies Record<Sprache, typeof de>
