import type { Sprache } from '../../lib/sprache'

// Dialog «Serviceheft» (ServiceBookDialog.vue) und Serviceheft-Scan (useServiceBookScan.ts)
const de = {
  titel: 'Serviceheft',
  fotografieren: 'Serviceheft-Seiten fotografieren oder PDF wählen',
  hinweisScan: 'Seite mit den Wartungsintervallen und Seiten mit Stempeln. Du kannst die Werte danach anpassen.',
  intervalle: 'Wartungsintervalle',
  intervalleHinweis: 'Was zuerst eintritt, Kilometer oder Monate. 0 heisst: gilt nicht. Zeilen ohne beides werden nicht gespeichert.',
  arbeit: 'Arbeit',
  kilometer: 'Kilometer',
  monate: 'Monate',
  monateEinheit: ' Mt.',
  bezeichnung: (art: string) => `Bezeichnung ${art}`,
  intervallKm: (arbeit: string) => `${arbeit} Intervall Kilometer`,
  intervallMonate: (arbeit: string) => `${arbeit} Intervall Monate`,
  entfernen: (arbeit: string) => `${arbeit} entfernen`,
  weitereArbeit: 'Weitere Arbeit',
  hinzufuegen: 'Hinzufügen',
  stempel: 'Stempel aus dem Serviceheft',
  stempelHinweis: 'Angekreuzte Einträge werden als erledigte Wartungen gespeichert. Handschrift liest die KI nicht immer richtig, darum vor dem Speichern Datum und Kilometer vergleichen.',
  uebernehmen: (eintrag: string) => `${eintrag} übernehmen`,
  schonErfasst: 'schon erfasst',
  kmPruefen: 'km prüfen',
  planSpeichern: 'Plan speichern',
  planUndEintraege: (n: number) => `Plan und ${n} ${n === 1 ? 'Eintrag' : 'Einträge'} speichern`,
  zusammenfassung: {
    intervalle: (n: number) => `${n} ${n === 1 ? 'Intervall' : 'Intervalle'} übernommen`,
    keineIntervalle: 'keine Hersteller-Intervalle gefunden',
    verworfen: (n: number) => `${n} aus einer Checkliste verworfen`,
    eintraege: (n: number) => `${n} ${n === 1 ? 'Eintrag' : 'Einträge'} gefunden`,
    keineStempel: 'keine Stempel gefunden',
    schonErfasst: (n: number) => `${n} schon erfasst`,
    unklarerKm: (n: number) => `${n} mit unklarem Kilometerstand`,
    bittePruefen: 'Bitte prüfen.',
  },
  scan: {
    seiteLesen: (i: number, n: number) => `Seite ${i} von ${n} wird gelesen …`,
    heftLesen: 'Serviceheft wird gelesen …',
    nurFotoPdf: (name: string) => `${name}: nur Fotos oder PDF möglich.`,
    zuGross: (name: string, mb: number) => `${name}: zu gross (max. ${mb} MB).`,
  },
}

export default {
  de,
  fr: {
    titel: 'Carnet d\'entretien',
    fotografieren: 'Photographier les pages du carnet ou choisir un PDF',
    hinweisScan: 'La page avec les intervalles d\'entretien et les pages avec les tampons. Tu peux adapter les valeurs ensuite.',
    intervalle: 'Intervalles d\'entretien',
    intervalleHinweis: 'Ce qui arrive en premier, kilomètres ou mois. 0 signifie : ne s\'applique pas. Les lignes sans l\'un ni l\'autre ne sont pas enregistrées.',
    arbeit: 'Travail',
    kilometer: 'Kilomètres',
    monate: 'Mois',
    monateEinheit: ' mois',
    bezeichnung: (art: string) => `Désignation ${art}`,
    intervallKm: (arbeit: string) => `${arbeit} intervalle kilomètres`,
    intervallMonate: (arbeit: string) => `${arbeit} intervalle mois`,
    entfernen: (arbeit: string) => `Retirer ${arbeit}`,
    weitereArbeit: 'Autre travail',
    hinzufuegen: 'Ajouter',
    stempel: 'Tampons du carnet d\'entretien',
    stempelHinweis: 'Les entrées cochées sont enregistrées comme entretiens faits. L\'IA ne lit pas toujours bien l\'écriture manuscrite : compare la date et les kilomètres avant d\'enregistrer.',
    uebernehmen: (eintrag: string) => `Reprendre ${eintrag}`,
    schonErfasst: 'déjà saisi',
    kmPruefen: 'vérifier les km',
    planSpeichern: 'Enregistrer le plan',
    planUndEintraege: (n: number) => `Enregistrer le plan et ${n} ${n === 1 ? 'entrée' : 'entrées'}`,
    zusammenfassung: {
      intervalle: (n: number) => `${n} ${n === 1 ? 'intervalle repris' : 'intervalles repris'}`,
      keineIntervalle: 'aucun intervalle du constructeur trouvé',
      verworfen: (n: number) => `${n} d'une liste de contrôle écarté(s)`,
      eintraege: (n: number) => `${n} ${n === 1 ? 'entrée trouvée' : 'entrées trouvées'}`,
      keineStempel: 'aucun tampon trouvé',
      schonErfasst: (n: number) => `${n} déjà saisi(s)`,
      unklarerKm: (n: number) => `${n} avec un kilométrage incertain`,
      bittePruefen: 'Vérifie-les.',
    },
    scan: {
      seiteLesen: (i: number, n: number) => `Lecture de la page ${i} sur ${n} …`,
      heftLesen: 'Lecture du carnet d\'entretien …',
      nurFotoPdf: (name: string) => `${name} : seulement des photos ou un PDF.`,
      zuGross: (name: string, mb: number) => `${name} : trop volumineux (max. ${mb} Mo).`,
    },
  },
  it: {
    titel: 'Libretto di manutenzione',
    fotografieren: 'Fotografa le pagine del libretto o scegli un PDF',
    hinweisScan: 'La pagina con gli intervalli di manutenzione e le pagine con i timbri. Puoi adattare i valori dopo.',
    intervalle: 'Intervalli di manutenzione',
    intervalleHinweis: 'Vale ciò che arriva prima, chilometri o mesi. 0 significa: non si applica. Le righe senza entrambi non vengono salvate.',
    arbeit: 'Lavoro',
    kilometer: 'Chilometri',
    monate: 'Mesi',
    monateEinheit: ' mesi',
    bezeichnung: (art: string) => `Denominazione ${art}`,
    intervallKm: (arbeit: string) => `${arbeit} intervallo chilometri`,
    intervallMonate: (arbeit: string) => `${arbeit} intervallo mesi`,
    entfernen: (arbeit: string) => `Rimuovi ${arbeit}`,
    weitereArbeit: 'Altro lavoro',
    hinzufuegen: 'Aggiungi',
    stempel: 'Timbri dal libretto di manutenzione',
    stempelHinweis: 'Le voci spuntate vengono salvate come manutenzioni fatte. L\'IA non legge sempre bene la scrittura a mano: prima di salvare confronta data e chilometri.',
    uebernehmen: (eintrag: string) => `Riprendi ${eintrag}`,
    schonErfasst: 'già registrato',
    kmPruefen: 'controlla km',
    planSpeichern: 'Salva il piano',
    planUndEintraege: (n: number) => `Salva il piano e ${n} ${n === 1 ? 'voce' : 'voci'}`,
    zusammenfassung: {
      intervalle: (n: number) => `${n} ${n === 1 ? 'intervallo ripreso' : 'intervalli ripresi'}`,
      keineIntervalle: 'nessun intervallo del costruttore trovato',
      verworfen: (n: number) => `${n} scartati da una lista di controllo`,
      eintraege: (n: number) => `${n} ${n === 1 ? 'voce trovata' : 'voci trovate'}`,
      keineStempel: 'nessun timbro trovato',
      schonErfasst: (n: number) => `${n} già registrati`,
      unklarerKm: (n: number) => `${n} con chilometraggio incerto`,
      bittePruefen: 'Controllali.',
    },
    scan: {
      seiteLesen: (i: number, n: number) => `Lettura della pagina ${i} di ${n} …`,
      heftLesen: 'Lettura del libretto di manutenzione …',
      nurFotoPdf: (name: string) => `${name}: solo foto o PDF.`,
      zuGross: (name: string, mb: number) => `${name}: troppo grande (max. ${mb} MB).`,
    },
  },
  en: {
    titel: 'Service book',
    fotografieren: 'Photograph service book pages or choose a PDF',
    hinweisScan: 'The page with the maintenance intervals and the pages with stamps. You can adjust the values afterwards.',
    intervalle: 'Maintenance intervals',
    intervalleHinweis: 'Whichever comes first, kilometres or months. 0 means: does not apply. Rows with neither are not saved.',
    arbeit: 'Job',
    kilometer: 'Kilometres',
    monate: 'Months',
    monateEinheit: ' mo.',
    bezeichnung: (art: string) => `Name ${art}`,
    intervallKm: (arbeit: string) => `${arbeit} interval kilometres`,
    intervallMonate: (arbeit: string) => `${arbeit} interval months`,
    entfernen: (arbeit: string) => `Remove ${arbeit}`,
    weitereArbeit: 'Another job',
    hinzufuegen: 'Add',
    stempel: 'Stamps from the service book',
    stempelHinweis: 'Ticked entries are saved as completed maintenance. The AI does not always read handwriting correctly, so compare the date and kilometres before saving.',
    uebernehmen: (eintrag: string) => `Take over ${eintrag}`,
    schonErfasst: 'already recorded',
    kmPruefen: 'check km',
    planSpeichern: 'Save schedule',
    planUndEintraege: (n: number) => `Save schedule and ${n} ${n === 1 ? 'entry' : 'entries'}`,
    zusammenfassung: {
      intervalle: (n: number) => `${n} ${n === 1 ? 'interval' : 'intervals'} taken over`,
      keineIntervalle: 'no manufacturer intervals found',
      verworfen: (n: number) => `${n} from a checklist discarded`,
      eintraege: (n: number) => `${n} ${n === 1 ? 'entry' : 'entries'} found`,
      keineStempel: 'no stamps found',
      schonErfasst: (n: number) => `${n} already recorded`,
      unklarerKm: (n: number) => `${n} with unclear mileage`,
      bittePruefen: 'Please check.',
    },
    scan: {
      seiteLesen: (i: number, n: number) => `Reading page ${i} of ${n} …`,
      heftLesen: 'Reading the service book …',
      nurFotoPdf: (name: string) => `${name}: only photos or PDF.`,
      zuGross: (name: string, mb: number) => `${name}: too large (max. ${mb} MB).`,
    },
  },
} satisfies Record<Sprache, typeof de>
