import type { Sprache } from '../../lib/sprache'

// Übersicht (DashboardPage.vue)
const de = {
  titel: 'Übersicht',
  rechnungFotografieren: 'Rechnung fotografieren',
  aboBestellen: 'Jahresabo bestellen',
  leer: 'Leg dein erstes Fahrzeug an. Mit dem Fahrzeugausweis geht es am schnellsten.',
  fahrzeugHinzufuegen: 'Fahrzeug hinzufügen',
  leerHinweis: 'Danach fotografierst du die erste Werkstattrechnung, den Rest liest Wartungsheft heraus.',
  gesamtkosten: 'Gesamtkosten',
  rechnungen: 'Rechnungen',
  faelligeArbeiten: 'Fällige Arbeiten',
  faellig: 'Fällig',
  nichtsFaellig: (km: string) => `Nichts überfällig und nichts in den nächsten 30 Tagen oder ${km} km fällig.`,
  erledigtEintragen: 'Erledigt eintragen',
  planHinweisEins: 'Dein Fahrzeug nutzt allgemeine Wartungsintervalle. Mit dem Serviceheft werden sie genau:',
  planHinweisAlle: 'Alle Fahrzeuge nutzen allgemeine Wartungsintervalle. Mit dem Serviceheft werden sie genau:',
  planHinweisAnzahl: (n: number) => `${n} ${n === 1 ? 'Fahrzeug nutzt' : 'Fahrzeuge nutzen'} allgemeine Wartungsintervalle. Mit dem Serviceheft werden sie genau:`,
  serviceheftFotografieren: 'Serviceheft fotografieren',
  serviceheftAria: (fahrzeug: string) => `Serviceheft ${fahrzeug}`,
  kostenTitel: 'Kosten pro Fahrzeug und Jahr',
  exportJahr: 'Jahr für den Jahresabschluss',
  export: 'Export',
  jahr: 'Jahr',
  fahrzeug: 'Fahrzeug',
  total: 'Total',
  umgerechnet: (n: number, waehrungen: string) => `${n} ${n === 1 ? 'Rechnung' : 'Rechnungen'} in ${waehrungen} zum EZB-Kurs am Rechnungsdatum umgerechnet.`,
  ohneKurs: (n: number) => `${n} ohne Kurs (offline?), in eigener Währung ausgewiesen.`,
  keineWartung: 'Noch keine Wartung erfasst',
  anzahlFaellig: (n: number) => `${n} fällig`,
  kmAendern: 'Kilometerstand ändern',
  kmAendernAria: (fahrzeug: string) => `Kilometerstand ${fahrzeug} ändern`,
  anzahlRechnungen: (n: number) => `${n} ${n === 1 ? 'Rechnung' : 'Rechnungen'}`,
  ohneWartungen: 'Ohne erfasste Wartungen kennt Wartungsheft keine Termine und schickt keine Erinnerung.',
  letzteWartungen: 'Letzte Wartungen eintragen',
  zuletzt: (datum: string) => `Zuletzt: ${datum}`,
  erledigtAria: (arbeit: string) => `${arbeit} erledigt eintragen`,
  erledigtTitel: (arbeit: string) => `${arbeit} erledigt`,
  ohneEintragAusblenden: 'Arbeiten ohne Eintrag ausblenden',
  ohneEintragAnzeigen: (n: number) => `${n} ${n === 1 ? 'Arbeit' : 'Arbeiten'} ohne Eintrag anzeigen`,
  welchesFahrzeug: 'Für welches Fahrzeug?',
  neueRechnung: 'Neue Rechnung',
  keineRechnungenJahr: (jahr: number) => `Keine Rechnungen aus ${jahr}.`,
  zipGeladen: (bilder: number) => `CSV und ${bilder} ${bilder === 1 ? 'Rechnungsbild' : 'Rechnungsbilder'} geladen.`,
  exportCsv: 'CSV für Excel, alle Fahrzeuge',
  exportPdf: 'PDF-Übersicht, alle Fahrzeuge',
  exportZip: (jahr: number) => `Jahresabschluss ${jahr}: ZIP mit CSV und Rechnungsbildern`,
}

export default {
  de,
  fr: {
    titel: 'Aperçu',
    rechnungFotografieren: 'Photographier une facture',
    aboBestellen: 'Commander l’abonnement annuel',
    leer: 'Ajoute ton premier véhicule. Le plus rapide, c’est avec le permis de circulation.',
    fahrzeugHinzufuegen: 'Ajouter un véhicule',
    leerHinweis: 'Ensuite, tu photographies la première facture du garage, Wartungsheft lit le reste.',
    gesamtkosten: 'Coûts totaux',
    rechnungen: 'Factures',
    faelligeArbeiten: 'Travaux à faire',
    faellig: 'À faire',
    nichtsFaellig: (km: string) => `Rien en retard et rien à faire dans les 30 prochains jours ou ${km} km.`,
    erledigtEintragen: 'Marquer comme fait',
    planHinweisEins: 'Ton véhicule utilise des intervalles d’entretien généraux. Avec le carnet d’entretien, ils deviennent précis :',
    planHinweisAlle: 'Tous les véhicules utilisent des intervalles d’entretien généraux. Avec le carnet d’entretien, ils deviennent précis :',
    planHinweisAnzahl: (n: number) => `${n} ${n === 1 ? 'véhicule utilise' : 'véhicules utilisent'} des intervalles d’entretien généraux. Avec le carnet d’entretien, ils deviennent précis :`,
    serviceheftFotografieren: 'Photographier le carnet d’entretien',
    serviceheftAria: (fahrzeug: string) => `Carnet d’entretien ${fahrzeug}`,
    kostenTitel: 'Coûts par véhicule et par année',
    exportJahr: 'Année du bouclement annuel',
    export: 'Exporter',
    jahr: 'Année',
    fahrzeug: 'Véhicule',
    total: 'Total',
    umgerechnet: (n: number, waehrungen: string) => `${n} ${n === 1 ? 'facture' : 'factures'} en ${waehrungen} ${n === 1 ? 'convertie' : 'converties'} au cours BCE du jour de la facture.`,
    ohneKurs: (n: number) => `${n} sans cours (hors ligne ?), indiquée${n === 1 ? '' : 's'} dans leur propre monnaie.`,
    keineWartung: 'Aucun entretien saisi',
    anzahlFaellig: (n: number) => `${n} à faire`,
    kmAendern: 'Modifier le kilométrage',
    kmAendernAria: (fahrzeug: string) => `Modifier le kilométrage de ${fahrzeug}`,
    anzahlRechnungen: (n: number) => `${n} ${n === 1 ? 'facture' : 'factures'}`,
    ohneWartungen: 'Sans entretien saisi, Wartungsheft ne connaît aucune échéance et n’envoie pas de rappel.',
    letzteWartungen: 'Saisir les derniers entretiens',
    zuletzt: (datum: string) => `Dernier : ${datum}`,
    erledigtAria: (arbeit: string) => `Marquer ${arbeit} comme fait`,
    erledigtTitel: (arbeit: string) => `${arbeit} fait`,
    ohneEintragAusblenden: 'Masquer les travaux sans entrée',
    ohneEintragAnzeigen: (n: number) => `Afficher ${n} ${n === 1 ? 'travail' : 'travaux'} sans entrée`,
    welchesFahrzeug: 'Pour quel véhicule ?',
    neueRechnung: 'Nouvelle facture',
    keineRechnungenJahr: (jahr: number) => `Aucune facture de ${jahr}.`,
    zipGeladen: (bilder: number) => `CSV et ${bilder} ${bilder === 1 ? 'image de facture téléchargée' : 'images de factures téléchargées'}.`,
    exportCsv: 'CSV pour Excel, tous les véhicules',
    exportPdf: 'Aperçu PDF, tous les véhicules',
    exportZip: (jahr: number) => `Bouclement ${jahr} : ZIP avec CSV et images des factures`,
  },
  it: {
    titel: 'Panoramica',
    rechnungFotografieren: 'Fotografa una fattura',
    aboBestellen: 'Ordina l\'abbonamento annuale',
    leer: 'Aggiungi il tuo primo veicolo. Con la licenza di circolazione è più veloce.',
    fahrzeugHinzufuegen: 'Aggiungi veicolo',
    leerHinweis: 'Poi fotografi la prima fattura dell\'officina, il resto lo legge Wartungsheft.',
    gesamtkosten: 'Costi totali',
    rechnungen: 'Fatture',
    faelligeArbeiten: 'Lavori in scadenza',
    faellig: 'In scadenza',
    nichtsFaellig: (km: string) => `Niente di scaduto e niente in scadenza nei prossimi 30 giorni o ${km} km.`,
    erledigtEintragen: 'Segna come fatto',
    planHinweisEins: 'Il tuo veicolo usa intervalli di manutenzione generici. Con il libretto di manutenzione diventano precisi:',
    planHinweisAlle: 'Tutti i veicoli usano intervalli di manutenzione generici. Con il libretto di manutenzione diventano precisi:',
    planHinweisAnzahl: (n: number) => `${n} ${n === 1 ? 'veicolo usa' : 'veicoli usano'} intervalli di manutenzione generici. Con il libretto di manutenzione diventano precisi:`,
    serviceheftFotografieren: 'Fotografa il libretto di manutenzione',
    serviceheftAria: (fahrzeug: string) => `Libretto di manutenzione ${fahrzeug}`,
    kostenTitel: 'Costi per veicolo e anno',
    exportJahr: 'Anno per la chiusura annuale',
    export: 'Esporta',
    jahr: 'Anno',
    fahrzeug: 'Veicolo',
    total: 'Totale',
    umgerechnet: (n: number, waehrungen: string) => `${n} ${n === 1 ? 'fattura' : 'fatture'} in ${waehrungen} ${n === 1 ? 'convertita' : 'convertite'} al cambio BCE della data della fattura.`,
    ohneKurs: (n: number) => `${n} senza cambio (offline?), ${n === 1 ? 'indicata' : 'indicate'} nella propria valuta.`,
    keineWartung: 'Nessuna manutenzione registrata',
    anzahlFaellig: (n: number) => `${n} in scadenza`,
    kmAendern: 'Modifica chilometraggio',
    kmAendernAria: (fahrzeug: string) => `Modifica il chilometraggio di ${fahrzeug}`,
    anzahlRechnungen: (n: number) => `${n} ${n === 1 ? 'fattura' : 'fatture'}`,
    ohneWartungen: 'Senza manutenzioni registrate, Wartungsheft non conosce scadenze e non invia promemoria.',
    letzteWartungen: 'Registra le ultime manutenzioni',
    zuletzt: (datum: string) => `Ultima: ${datum}`,
    erledigtAria: (arbeit: string) => `Segna ${arbeit} come fatto`,
    erledigtTitel: (arbeit: string) => `${arbeit} fatto`,
    ohneEintragAusblenden: 'Nascondi i lavori senza registrazione',
    ohneEintragAnzeigen: (n: number) => `Mostra ${n} ${n === 1 ? 'lavoro' : 'lavori'} senza registrazione`,
    welchesFahrzeug: 'Per quale veicolo?',
    neueRechnung: 'Nuova fattura',
    keineRechnungenJahr: (jahr: number) => `Nessuna fattura del ${jahr}.`,
    zipGeladen: (bilder: number) => `CSV e ${bilder} ${bilder === 1 ? 'immagine della fattura scaricata' : 'immagini delle fatture scaricate'}.`,
    exportCsv: 'CSV per Excel, tutti i veicoli',
    exportPdf: 'Panoramica PDF, tutti i veicoli',
    exportZip: (jahr: number) => `Chiusura ${jahr}: ZIP con CSV e immagini delle fatture`,
  },
  en: {
    titel: 'Overview',
    rechnungFotografieren: 'Photograph an invoice',
    aboBestellen: 'Order annual subscription',
    leer: 'Add your first vehicle. The vehicle registration document is the quickest way.',
    fahrzeugHinzufuegen: 'Add vehicle',
    leerHinweis: 'Then photograph your first garage invoice, Wartungsheft reads out the rest.',
    gesamtkosten: 'Total costs',
    rechnungen: 'Invoices',
    faelligeArbeiten: 'Work due',
    faellig: 'Due',
    nichtsFaellig: (km: string) => `Nothing overdue and nothing due in the next 30 days or ${km} km.`,
    erledigtEintragen: 'Mark as done',
    planHinweisEins: 'Your vehicle uses general maintenance intervals. With the service book they become exact:',
    planHinweisAlle: 'All vehicles use general maintenance intervals. With the service book they become exact:',
    planHinweisAnzahl: (n: number) => `${n} ${n === 1 ? 'vehicle uses' : 'vehicles use'} general maintenance intervals. With the service book they become exact:`,
    serviceheftFotografieren: 'Photograph the service book',
    serviceheftAria: (fahrzeug: string) => `Service book ${fahrzeug}`,
    kostenTitel: 'Costs per vehicle and year',
    exportJahr: 'Year for the annual statement',
    export: 'Export',
    jahr: 'Year',
    fahrzeug: 'Vehicle',
    total: 'Total',
    umgerechnet: (n: number, waehrungen: string) => `${n} ${n === 1 ? 'invoice' : 'invoices'} in ${waehrungen} converted at the ECB rate on the invoice date.`,
    ohneKurs: (n: number) => `${n} without a rate (offline?), shown in their own currency.`,
    keineWartung: 'No maintenance recorded yet',
    anzahlFaellig: (n: number) => `${n} due`,
    kmAendern: 'Change mileage',
    kmAendernAria: (fahrzeug: string) => `Change mileage of ${fahrzeug}`,
    anzahlRechnungen: (n: number) => `${n} ${n === 1 ? 'invoice' : 'invoices'}`,
    ohneWartungen: 'Without recorded maintenance, Wartungsheft knows no due dates and sends no reminders.',
    letzteWartungen: 'Enter recent maintenance',
    zuletzt: (datum: string) => `Last: ${datum}`,
    erledigtAria: (arbeit: string) => `Mark ${arbeit} as done`,
    erledigtTitel: (arbeit: string) => `${arbeit} done`,
    ohneEintragAusblenden: 'Hide work without an entry',
    ohneEintragAnzeigen: (n: number) => `Show ${n} ${n === 1 ? 'job' : 'jobs'} without an entry`,
    welchesFahrzeug: 'Which vehicle?',
    neueRechnung: 'New invoice',
    keineRechnungenJahr: (jahr: number) => `No invoices from ${jahr}.`,
    zipGeladen: (bilder: number) => `CSV and ${bilder} ${bilder === 1 ? 'invoice image' : 'invoice images'} downloaded.`,
    exportCsv: 'CSV for Excel, all vehicles',
    exportPdf: 'PDF overview, all vehicles',
    exportZip: (jahr: number) => `Annual statement ${jahr}: ZIP with CSV and invoice images`,
  },
} satisfies Record<Sprache, typeof de>
